/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { PayvraError } from "./payvraerror.js";

/**
 * The error information
 */
export type ErrorUNAUTHORIZEDData = {
  /**
   * The error message
   */
  message: string;
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ErrorUNAUTHORIZEDIssue> | undefined;
};

/**
 * The error information
 */
export class ErrorUNAUTHORIZED extends PayvraError {
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ErrorUNAUTHORIZEDIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorUNAUTHORIZEDData;

  constructor(
    err: ErrorUNAUTHORIZEDData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "ErrorUNAUTHORIZED";
  }
}

/** @internal */
export const ErrorUNAUTHORIZED$inboundSchema: z.ZodType<
  ErrorUNAUTHORIZED,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(z.lazy(() => models.ErrorUNAUTHORIZEDIssue$inboundSchema))
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorUNAUTHORIZED(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ErrorUNAUTHORIZED$Outbound = {
  message: string;
  code: string;
  issues?: Array<models.ErrorUNAUTHORIZEDIssue$Outbound> | undefined;
};

/** @internal */
export const ErrorUNAUTHORIZED$outboundSchema: z.ZodType<
  ErrorUNAUTHORIZED$Outbound,
  z.ZodTypeDef,
  ErrorUNAUTHORIZED
> = z.instanceof(ErrorUNAUTHORIZED)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(z.lazy(() => models.ErrorUNAUTHORIZEDIssue$outboundSchema))
      .optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorUNAUTHORIZED$ {
  /** @deprecated use `ErrorUNAUTHORIZED$inboundSchema` instead. */
  export const inboundSchema = ErrorUNAUTHORIZED$inboundSchema;
  /** @deprecated use `ErrorUNAUTHORIZED$outboundSchema` instead. */
  export const outboundSchema = ErrorUNAUTHORIZED$outboundSchema;
  /** @deprecated use `ErrorUNAUTHORIZED$Outbound` instead. */
  export type Outbound = ErrorUNAUTHORIZED$Outbound;
}
