/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { PayvraError } from "./payvraerror.js";

/**
 * The error information
 */
export type ErrorFORBIDDENData = {
  /**
   * The error message
   */
  message: string;
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ErrorFORBIDDENIssue> | undefined;
};

/**
 * The error information
 */
export class ErrorFORBIDDEN extends PayvraError {
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ErrorFORBIDDENIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorFORBIDDENData;

  constructor(
    err: ErrorFORBIDDENData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "ErrorFORBIDDEN";
  }
}

/** @internal */
export const ErrorFORBIDDEN$inboundSchema: z.ZodType<
  ErrorFORBIDDEN,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(z.lazy(() => models.ErrorFORBIDDENIssue$inboundSchema))
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorFORBIDDEN(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ErrorFORBIDDEN$Outbound = {
  message: string;
  code: string;
  issues?: Array<models.ErrorFORBIDDENIssue$Outbound> | undefined;
};

/** @internal */
export const ErrorFORBIDDEN$outboundSchema: z.ZodType<
  ErrorFORBIDDEN$Outbound,
  z.ZodTypeDef,
  ErrorFORBIDDEN
> = z.instanceof(ErrorFORBIDDEN)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(z.lazy(() => models.ErrorFORBIDDENIssue$outboundSchema))
      .optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorFORBIDDEN$ {
  /** @deprecated use `ErrorFORBIDDEN$inboundSchema` instead. */
  export const inboundSchema = ErrorFORBIDDEN$inboundSchema;
  /** @deprecated use `ErrorFORBIDDEN$outboundSchema` instead. */
  export const outboundSchema = ErrorFORBIDDEN$outboundSchema;
  /** @deprecated use `ErrorFORBIDDEN$Outbound` instead. */
  export type Outbound = ErrorFORBIDDEN$Outbound;
}
