/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { PayvraError } from "./payvraerror.js";

/**
 * The error information
 */
export type ErrorNOTFOUNDData = {
  /**
   * The error message
   */
  message: string;
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ErrorNOTFOUNDIssue> | undefined;
};

/**
 * The error information
 */
export class ErrorNOTFOUND extends PayvraError {
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ErrorNOTFOUNDIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorNOTFOUNDData;

  constructor(
    err: ErrorNOTFOUNDData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "ErrorNOTFOUND";
  }
}

/** @internal */
export const ErrorNOTFOUND$inboundSchema: z.ZodType<
  ErrorNOTFOUND,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(z.lazy(() => models.ErrorNOTFOUNDIssue$inboundSchema))
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorNOTFOUND(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ErrorNOTFOUND$Outbound = {
  message: string;
  code: string;
  issues?: Array<models.ErrorNOTFOUNDIssue$Outbound> | undefined;
};

/** @internal */
export const ErrorNOTFOUND$outboundSchema: z.ZodType<
  ErrorNOTFOUND$Outbound,
  z.ZodTypeDef,
  ErrorNOTFOUND
> = z.instanceof(ErrorNOTFOUND)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(z.lazy(() => models.ErrorNOTFOUNDIssue$outboundSchema))
      .optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorNOTFOUND$ {
  /** @deprecated use `ErrorNOTFOUND$inboundSchema` instead. */
  export const inboundSchema = ErrorNOTFOUND$inboundSchema;
  /** @deprecated use `ErrorNOTFOUND$outboundSchema` instead. */
  export const outboundSchema = ErrorNOTFOUND$outboundSchema;
  /** @deprecated use `ErrorNOTFOUND$Outbound` instead. */
  export type Outbound = ErrorNOTFOUND$Outbound;
}
