/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { PayvraError } from "./payvraerror.js";

/**
 * The error information
 */
export type ErrorBADREQUESTData = {
  /**
   * The error message
   */
  message: string;
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ErrorBADREQUESTIssue> | undefined;
};

/**
 * The error information
 */
export class ErrorBADREQUEST extends PayvraError {
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ErrorBADREQUESTIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorBADREQUESTData;

  constructor(
    err: ErrorBADREQUESTData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "ErrorBADREQUEST";
  }
}

/** @internal */
export const ErrorBADREQUEST$inboundSchema: z.ZodType<
  ErrorBADREQUEST,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(z.lazy(() => models.ErrorBADREQUESTIssue$inboundSchema))
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorBADREQUEST(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ErrorBADREQUEST$Outbound = {
  message: string;
  code: string;
  issues?: Array<models.ErrorBADREQUESTIssue$Outbound> | undefined;
};

/** @internal */
export const ErrorBADREQUEST$outboundSchema: z.ZodType<
  ErrorBADREQUEST$Outbound,
  z.ZodTypeDef,
  ErrorBADREQUEST
> = z.instanceof(ErrorBADREQUEST)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(z.lazy(() => models.ErrorBADREQUESTIssue$outboundSchema))
      .optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorBADREQUEST$ {
  /** @deprecated use `ErrorBADREQUEST$inboundSchema` instead. */
  export const inboundSchema = ErrorBADREQUEST$inboundSchema;
  /** @deprecated use `ErrorBADREQUEST$outboundSchema` instead. */
  export const outboundSchema = ErrorBADREQUEST$outboundSchema;
  /** @deprecated use `ErrorBADREQUEST$Outbound` instead. */
  export type Outbound = ErrorBADREQUEST$Outbound;
}
