/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { PayvraError } from "./payvraerror.js";

/**
 * The error information
 */
export type ErrorinternalservererrorData = {
  /**
   * The error message
   */
  message: string;
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ERRORINTERNALSERVERERRORIssue> | undefined;
};

/**
 * The error information
 */
export class Errorinternalservererror extends PayvraError {
  /**
   * The error code
   */
  code: string;
  /**
   * An array of issues that were responsible for the error
   */
  issues?: Array<models.ERRORINTERNALSERVERERRORIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorinternalservererrorData;

  constructor(
    err: ErrorinternalservererrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "Errorinternalservererror";
  }
}

/** @internal */
export const Errorinternalservererror$inboundSchema: z.ZodType<
  Errorinternalservererror,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => models.ERRORINTERNALSERVERERRORIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new Errorinternalservererror(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type Errorinternalservererror$Outbound = {
  message: string;
  code: string;
  issues?: Array<models.ERRORINTERNALSERVERERRORIssue$Outbound> | undefined;
};

/** @internal */
export const Errorinternalservererror$outboundSchema: z.ZodType<
  Errorinternalservererror$Outbound,
  z.ZodTypeDef,
  Errorinternalservererror
> = z.instanceof(Errorinternalservererror)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => models.ERRORINTERNALSERVERERRORIssue$outboundSchema),
    ).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Errorinternalservererror$ {
  /** @deprecated use `Errorinternalservererror$inboundSchema` instead. */
  export const inboundSchema = Errorinternalservererror$inboundSchema;
  /** @deprecated use `Errorinternalservererror$outboundSchema` instead. */
  export const outboundSchema = Errorinternalservererror$outboundSchema;
  /** @deprecated use `Errorinternalservererror$Outbound` instead. */
  export type Outbound = Errorinternalservererror$Outbound;
}
