/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversionsCreate } from "../funcs/conversionsCreate.js";
import { conversionsEstimate } from "../funcs/conversionsEstimate.js";
import { conversionsGet } from "../funcs/conversionsGet.js";
import { conversionsList } from "../funcs/conversionsList.js";
import { conversionsStats } from "../funcs/conversionsStats.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Conversions extends ClientSDK {
  /**
   * Query conversions
   *
   * @remarks
   * Query conversions for the authenticated merchant.
   */
  async list(
    request?: operations.ConversionsListOwnedRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ConversionsListOwnedResponse> {
    return unwrapAsync(conversionsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a conversion
   *
   * @remarks
   * Retrieve a conversion by its ID for the authenticated merchant.
   */
  async get(
    request: operations.ConversionsGetByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.ConversionsGetByIdResponse> {
    return unwrapAsync(conversionsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get conversion estimate
   *
   * @remarks
   * Get the fee estimate for a currency.
   */
  async estimate(
    request: operations.ConversionsGetEstimateRequest,
    options?: RequestOptions,
  ): Promise<operations.ConversionsGetEstimateResponse> {
    return unwrapAsync(conversionsEstimate(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a conversion
   *
   * @remarks
   * Create a conversion for the authenticated merchant.
   */
  async create(
    request: operations.ConversionsCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.ConversionsCreateResponse> {
    return unwrapAsync(conversionsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get conversion stats
   *
   * @remarks
   * Get conversion stats for the authenticated merchant.
   */
  async stats(
    options?: RequestOptions,
  ): Promise<operations.ConversionsGetStatsResponse> {
    return unwrapAsync(conversionsStats(
      this,
      options,
    ));
  }
}
