/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { currenciesAll } from "../funcs/currenciesAll.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Currencies extends ClientSDK {
  /**
   * Read all currencies
   */
  async all(
    options?: RequestOptions,
  ): Promise<Array<operations.CurrenciesGetAllResponse>> {
    return unwrapAsync(currenciesAll(
      this,
      options,
    ));
  }
}
