/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentInvoicesCreate } from "../funcs/paymentInvoicesCreate.js";
import { paymentInvoicesCreateWhiteLabel } from "../funcs/paymentInvoicesCreateWhiteLabel.js";
import { paymentInvoicesGet } from "../funcs/paymentInvoicesGet.js";
import { paymentInvoicesList } from "../funcs/paymentInvoicesList.js";
import { paymentInvoicesStats } from "../funcs/paymentInvoicesStats.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PaymentInvoices extends ClientSDK {
  /**
   * Query payment invoices
   */
  async list(
    request?: operations.PaymentInvoicesListOwnedRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PaymentInvoicesListOwnedResponse> {
    return unwrapAsync(paymentInvoicesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a payment invoice
   *
   * @remarks
   * Retrieve a payment invoice by its ID for the authenticated merchant.
   */
  async get(
    request: operations.PaymentInvoicesGetByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PaymentInvoicesGetByIdResponse> {
    return unwrapAsync(paymentInvoicesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get payment invoice stats
   *
   * @remarks
   * Get payment invoice stats for the authenticated merchant.
   */
  async stats(
    options?: RequestOptions,
  ): Promise<operations.PaymentInvoicesGetStatsResponse> {
    return unwrapAsync(paymentInvoicesStats(
      this,
      options,
    ));
  }

  /**
   * Create a payment invoice
   */
  async create(
    request: operations.PaymentInvoicesCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.PaymentInvoicesCreateResponse> {
    return unwrapAsync(paymentInvoicesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a white label payment invoice
   */
  async createWhiteLabel(
    request: operations.PaymentInvoicesCreateWhiteLabelRequest,
    options?: RequestOptions,
  ): Promise<operations.PaymentInvoicesCreateWhiteLabelResponse> {
    return unwrapAsync(paymentInvoicesCreateWhiteLabel(
      this,
      request,
      options,
    ));
  }
}
