/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { payoutsCreate } from "../funcs/payoutsCreate.js";
import { payoutsFeeEstimate } from "../funcs/payoutsFeeEstimate.js";
import { payoutsGet } from "../funcs/payoutsGet.js";
import { payoutsList } from "../funcs/payoutsList.js";
import { payoutsMinAmount } from "../funcs/payoutsMinAmount.js";
import { payoutsStats } from "../funcs/payoutsStats.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payouts extends ClientSDK {
  /**
   * Query payouts
   *
   * @remarks
   * Query payouts for the authenticated merchant.
   */
  async list(
    request?: operations.PayoutsListOwnedRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PayoutsListOwnedResponse> {
    return unwrapAsync(payoutsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a payout
   *
   * @remarks
   * Retrieve a payout by its ID for the authenticated merchant.
   */
  async get(
    request: operations.PayoutsGetByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PayoutsGetByIdResponse> {
    return unwrapAsync(payoutsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get minimum payout amount
   *
   * @remarks
   * Get the minimum amount for a currency.
   */
  async minAmount(
    request: operations.PayoutsGetMinAmountRequest,
    options?: RequestOptions,
  ): Promise<operations.PayoutsGetMinAmountResponse> {
    return unwrapAsync(payoutsMinAmount(
      this,
      request,
      options,
    ));
  }

  /**
   * Get payout fee estimate
   *
   * @remarks
   * Get the fee estimate for a currency.
   */
  async feeEstimate(
    request: operations.PayoutsGetFeeEstimateRequest,
    options?: RequestOptions,
  ): Promise<operations.PayoutsGetFeeEstimateResponse> {
    return unwrapAsync(payoutsFeeEstimate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get payout stats
   *
   * @remarks
   * Get payout stats the authenticated merchant.
   */
  async stats(
    options?: RequestOptions,
  ): Promise<operations.PayoutsGetStatsResponse> {
    return unwrapAsync(payoutsStats(
      this,
      options,
    ));
  }

  /**
   * Create a payout
   *
   * @remarks
   * Create a payout for the authenticated merchant.
   */
  async create(
    request: operations.PayoutsCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.PayoutsCreateResponse> {
    return unwrapAsync(payoutsCreate(
      this,
      request,
      options,
    ));
  }
}
