/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Conversions } from "./conversions.js";
import { Currencies } from "./currencies.js";
import { PaymentInvoices } from "./paymentinvoices.js";
import { Payouts } from "./payouts.js";
import { Wallets } from "./wallets.js";

export class Payvra extends ClientSDK {
  private _currencies?: Currencies;
  get currencies(): Currencies {
    return (this._currencies ??= new Currencies(this._options));
  }

  private _wallets?: Wallets;
  get wallets(): Wallets {
    return (this._wallets ??= new Wallets(this._options));
  }

  private _paymentInvoices?: PaymentInvoices;
  get paymentInvoices(): PaymentInvoices {
    return (this._paymentInvoices ??= new PaymentInvoices(this._options));
  }

  private _payouts?: Payouts;
  get payouts(): Payouts {
    return (this._payouts ??= new Payouts(this._options));
  }

  private _conversions?: Conversions;
  get conversions(): Conversions {
    return (this._conversions ??= new Conversions(this._options));
  }
}
