/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsGet } from "../funcs/walletsGet.js";
import { walletsList } from "../funcs/walletsList.js";
import { walletsListOwned } from "../funcs/walletsListOwned.js";
import { walletsStats } from "../funcs/walletsStats.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Wallets extends ClientSDK {
  /**
   * Query wallets
   */
  async list(
    request?: operations.WalletsListOwnedRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.WalletsListOwnedResponse> {
    return unwrapAsync(walletsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a wallet
   *
   * @remarks
   * Retrieve a wallet by its ID for the authenticated merchant
   */
  async get(
    request: operations.WalletsGetByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.WalletsGetByIdResponse> {
    return unwrapAsync(walletsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all wallets
   *
   * @remarks
   * Get all wallets for the authenticated merchant.
   */
  async listOwned(
    options?: RequestOptions,
  ): Promise<Array<operations.WalletsGetAllOwnedResponse>> {
    return unwrapAsync(walletsListOwned(
      this,
      options,
    ));
  }

  /**
   * Get wallet stats
   *
   * @remarks
   * Get wallet stats for the authenticated merchant.
   */
  async stats(
    options?: RequestOptions,
  ): Promise<operations.WalletsGetStatsResponse> {
    return unwrapAsync(walletsStats(
      this,
      options,
    ));
  }
}
