/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the payvra SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx currenciesAll.example.ts
 */

import { Payvra } from "payvra";

const payvra = new Payvra({
  apiKey: process.env["PAYVRA_API_KEY"] ?? "",
});

async function main() {
  const result = await payvra.all();

  console.log(result);
}

main().catch(console.error);
