/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConversionsGetEstimateRequest = {
  amountFrom: string;
  currencyFrom: string;
  currencyTo: string;
};

/**
 * Successful response
 */
export type ConversionsGetEstimateResponse = {
  amountTo: string;
};

/** @internal */
export const ConversionsGetEstimateRequest$inboundSchema: z.ZodType<
  ConversionsGetEstimateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  amountFrom: z.string(),
  currencyFrom: z.string(),
  currencyTo: z.string(),
});

/** @internal */
export type ConversionsGetEstimateRequest$Outbound = {
  amountFrom: string;
  currencyFrom: string;
  currencyTo: string;
};

/** @internal */
export const ConversionsGetEstimateRequest$outboundSchema: z.ZodType<
  ConversionsGetEstimateRequest$Outbound,
  z.ZodTypeDef,
  ConversionsGetEstimateRequest
> = z.object({
  amountFrom: z.string(),
  currencyFrom: z.string(),
  currencyTo: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsGetEstimateRequest$ {
  /** @deprecated use `ConversionsGetEstimateRequest$inboundSchema` instead. */
  export const inboundSchema = ConversionsGetEstimateRequest$inboundSchema;
  /** @deprecated use `ConversionsGetEstimateRequest$outboundSchema` instead. */
  export const outboundSchema = ConversionsGetEstimateRequest$outboundSchema;
  /** @deprecated use `ConversionsGetEstimateRequest$Outbound` instead. */
  export type Outbound = ConversionsGetEstimateRequest$Outbound;
}

export function conversionsGetEstimateRequestToJSON(
  conversionsGetEstimateRequest: ConversionsGetEstimateRequest,
): string {
  return JSON.stringify(
    ConversionsGetEstimateRequest$outboundSchema.parse(
      conversionsGetEstimateRequest,
    ),
  );
}

export function conversionsGetEstimateRequestFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsGetEstimateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsGetEstimateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsGetEstimateRequest' from JSON`,
  );
}

/** @internal */
export const ConversionsGetEstimateResponse$inboundSchema: z.ZodType<
  ConversionsGetEstimateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  amountTo: z.string(),
});

/** @internal */
export type ConversionsGetEstimateResponse$Outbound = {
  amountTo: string;
};

/** @internal */
export const ConversionsGetEstimateResponse$outboundSchema: z.ZodType<
  ConversionsGetEstimateResponse$Outbound,
  z.ZodTypeDef,
  ConversionsGetEstimateResponse
> = z.object({
  amountTo: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsGetEstimateResponse$ {
  /** @deprecated use `ConversionsGetEstimateResponse$inboundSchema` instead. */
  export const inboundSchema = ConversionsGetEstimateResponse$inboundSchema;
  /** @deprecated use `ConversionsGetEstimateResponse$outboundSchema` instead. */
  export const outboundSchema = ConversionsGetEstimateResponse$outboundSchema;
  /** @deprecated use `ConversionsGetEstimateResponse$Outbound` instead. */
  export type Outbound = ConversionsGetEstimateResponse$Outbound;
}

export function conversionsGetEstimateResponseToJSON(
  conversionsGetEstimateResponse: ConversionsGetEstimateResponse,
): string {
  return JSON.stringify(
    ConversionsGetEstimateResponse$outboundSchema.parse(
      conversionsGetEstimateResponse,
    ),
  );
}

export function conversionsGetEstimateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsGetEstimateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsGetEstimateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsGetEstimateResponse' from JSON`,
  );
}
