/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConversionsListOwnedFilter = {
  createdStart?: string | null | undefined;
  createdEnd?: string | null | undefined;
  merchants?: Array<string> | null | undefined;
  q?: string | null | undefined;
};

export type ConversionsListOwnedRequest = {
  filter?: ConversionsListOwnedFilter | undefined;
  sort?: Array<string> | null | undefined;
  cursor?: string | undefined;
  pageSize?: number | undefined;
};

export type ConversionsListOwnedCursor = string | any;

export type ConversionsListOwnedMeta = {
  cursor?: string | any | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

export const ConversionsListOwnedStatus = {
  Waiting: "waiting",
  Processing: "processing",
  Finished: "finished",
  Rejected: "rejected",
} as const;
export type ConversionsListOwnedStatus = ClosedEnum<
  typeof ConversionsListOwnedStatus
>;

export type ConversionsListOwnedCurrencyFrom = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ConversionsListOwnedCurrencyTo = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ConversionsListOwnedData = {
  id: string;
  merchantId: string;
  walletFromId: string;
  walletToId: string;
  status: ConversionsListOwnedStatus;
  amountFrom: string;
  amountTo: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currencyFrom: ConversionsListOwnedCurrencyFrom;
  currencyTo: ConversionsListOwnedCurrencyTo;
};

/**
 * Successful response
 */
export type ConversionsListOwnedResponse = {
  meta: ConversionsListOwnedMeta;
  data: Array<ConversionsListOwnedData>;
};

/** @internal */
export const ConversionsListOwnedFilter$inboundSchema: z.ZodType<
  ConversionsListOwnedFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_start: z.nullable(z.string()).optional(),
  created_end: z.nullable(z.string()).optional(),
  merchants: z.nullable(z.array(z.string())).optional(),
  q: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_start": "createdStart",
    "created_end": "createdEnd",
  });
});

/** @internal */
export type ConversionsListOwnedFilter$Outbound = {
  created_start?: string | null | undefined;
  created_end?: string | null | undefined;
  merchants?: Array<string> | null | undefined;
  q?: string | null | undefined;
};

/** @internal */
export const ConversionsListOwnedFilter$outboundSchema: z.ZodType<
  ConversionsListOwnedFilter$Outbound,
  z.ZodTypeDef,
  ConversionsListOwnedFilter
> = z.object({
  createdStart: z.nullable(z.string()).optional(),
  createdEnd: z.nullable(z.string()).optional(),
  merchants: z.nullable(z.array(z.string())).optional(),
  q: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    createdStart: "created_start",
    createdEnd: "created_end",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedFilter$ {
  /** @deprecated use `ConversionsListOwnedFilter$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedFilter$inboundSchema;
  /** @deprecated use `ConversionsListOwnedFilter$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedFilter$outboundSchema;
  /** @deprecated use `ConversionsListOwnedFilter$Outbound` instead. */
  export type Outbound = ConversionsListOwnedFilter$Outbound;
}

export function conversionsListOwnedFilterToJSON(
  conversionsListOwnedFilter: ConversionsListOwnedFilter,
): string {
  return JSON.stringify(
    ConversionsListOwnedFilter$outboundSchema.parse(conversionsListOwnedFilter),
  );
}

export function conversionsListOwnedFilterFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsListOwnedFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsListOwnedFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsListOwnedFilter' from JSON`,
  );
}

/** @internal */
export const ConversionsListOwnedRequest$inboundSchema: z.ZodType<
  ConversionsListOwnedRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filter: z.lazy(() => ConversionsListOwnedFilter$inboundSchema).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  cursor: z.string().optional(),
  pageSize: z.number().optional(),
});

/** @internal */
export type ConversionsListOwnedRequest$Outbound = {
  filter?: ConversionsListOwnedFilter$Outbound | undefined;
  sort?: Array<string> | null | undefined;
  cursor?: string | undefined;
  pageSize?: number | undefined;
};

/** @internal */
export const ConversionsListOwnedRequest$outboundSchema: z.ZodType<
  ConversionsListOwnedRequest$Outbound,
  z.ZodTypeDef,
  ConversionsListOwnedRequest
> = z.object({
  filter: z.lazy(() => ConversionsListOwnedFilter$outboundSchema).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  cursor: z.string().optional(),
  pageSize: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedRequest$ {
  /** @deprecated use `ConversionsListOwnedRequest$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedRequest$inboundSchema;
  /** @deprecated use `ConversionsListOwnedRequest$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedRequest$outboundSchema;
  /** @deprecated use `ConversionsListOwnedRequest$Outbound` instead. */
  export type Outbound = ConversionsListOwnedRequest$Outbound;
}

export function conversionsListOwnedRequestToJSON(
  conversionsListOwnedRequest: ConversionsListOwnedRequest,
): string {
  return JSON.stringify(
    ConversionsListOwnedRequest$outboundSchema.parse(
      conversionsListOwnedRequest,
    ),
  );
}

export function conversionsListOwnedRequestFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsListOwnedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsListOwnedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsListOwnedRequest' from JSON`,
  );
}

/** @internal */
export const ConversionsListOwnedCursor$inboundSchema: z.ZodType<
  ConversionsListOwnedCursor,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.any()]);

/** @internal */
export type ConversionsListOwnedCursor$Outbound = string | any;

/** @internal */
export const ConversionsListOwnedCursor$outboundSchema: z.ZodType<
  ConversionsListOwnedCursor$Outbound,
  z.ZodTypeDef,
  ConversionsListOwnedCursor
> = z.union([z.string(), z.any()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedCursor$ {
  /** @deprecated use `ConversionsListOwnedCursor$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedCursor$inboundSchema;
  /** @deprecated use `ConversionsListOwnedCursor$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedCursor$outboundSchema;
  /** @deprecated use `ConversionsListOwnedCursor$Outbound` instead. */
  export type Outbound = ConversionsListOwnedCursor$Outbound;
}

export function conversionsListOwnedCursorToJSON(
  conversionsListOwnedCursor: ConversionsListOwnedCursor,
): string {
  return JSON.stringify(
    ConversionsListOwnedCursor$outboundSchema.parse(conversionsListOwnedCursor),
  );
}

export function conversionsListOwnedCursorFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsListOwnedCursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsListOwnedCursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsListOwnedCursor' from JSON`,
  );
}

/** @internal */
export const ConversionsListOwnedMeta$inboundSchema: z.ZodType<
  ConversionsListOwnedMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.union([z.string(), z.any()]).optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/** @internal */
export type ConversionsListOwnedMeta$Outbound = {
  cursor?: string | any | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/** @internal */
export const ConversionsListOwnedMeta$outboundSchema: z.ZodType<
  ConversionsListOwnedMeta$Outbound,
  z.ZodTypeDef,
  ConversionsListOwnedMeta
> = z.object({
  cursor: z.union([z.string(), z.any()]).optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedMeta$ {
  /** @deprecated use `ConversionsListOwnedMeta$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedMeta$inboundSchema;
  /** @deprecated use `ConversionsListOwnedMeta$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedMeta$outboundSchema;
  /** @deprecated use `ConversionsListOwnedMeta$Outbound` instead. */
  export type Outbound = ConversionsListOwnedMeta$Outbound;
}

export function conversionsListOwnedMetaToJSON(
  conversionsListOwnedMeta: ConversionsListOwnedMeta,
): string {
  return JSON.stringify(
    ConversionsListOwnedMeta$outboundSchema.parse(conversionsListOwnedMeta),
  );
}

export function conversionsListOwnedMetaFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsListOwnedMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsListOwnedMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsListOwnedMeta' from JSON`,
  );
}

/** @internal */
export const ConversionsListOwnedStatus$inboundSchema: z.ZodNativeEnum<
  typeof ConversionsListOwnedStatus
> = z.nativeEnum(ConversionsListOwnedStatus);

/** @internal */
export const ConversionsListOwnedStatus$outboundSchema: z.ZodNativeEnum<
  typeof ConversionsListOwnedStatus
> = ConversionsListOwnedStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedStatus$ {
  /** @deprecated use `ConversionsListOwnedStatus$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedStatus$inboundSchema;
  /** @deprecated use `ConversionsListOwnedStatus$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedStatus$outboundSchema;
}

/** @internal */
export const ConversionsListOwnedCurrencyFrom$inboundSchema: z.ZodType<
  ConversionsListOwnedCurrencyFrom,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type ConversionsListOwnedCurrencyFrom$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const ConversionsListOwnedCurrencyFrom$outboundSchema: z.ZodType<
  ConversionsListOwnedCurrencyFrom$Outbound,
  z.ZodTypeDef,
  ConversionsListOwnedCurrencyFrom
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedCurrencyFrom$ {
  /** @deprecated use `ConversionsListOwnedCurrencyFrom$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedCurrencyFrom$inboundSchema;
  /** @deprecated use `ConversionsListOwnedCurrencyFrom$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedCurrencyFrom$outboundSchema;
  /** @deprecated use `ConversionsListOwnedCurrencyFrom$Outbound` instead. */
  export type Outbound = ConversionsListOwnedCurrencyFrom$Outbound;
}

export function conversionsListOwnedCurrencyFromToJSON(
  conversionsListOwnedCurrencyFrom: ConversionsListOwnedCurrencyFrom,
): string {
  return JSON.stringify(
    ConversionsListOwnedCurrencyFrom$outboundSchema.parse(
      conversionsListOwnedCurrencyFrom,
    ),
  );
}

export function conversionsListOwnedCurrencyFromFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsListOwnedCurrencyFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsListOwnedCurrencyFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsListOwnedCurrencyFrom' from JSON`,
  );
}

/** @internal */
export const ConversionsListOwnedCurrencyTo$inboundSchema: z.ZodType<
  ConversionsListOwnedCurrencyTo,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type ConversionsListOwnedCurrencyTo$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const ConversionsListOwnedCurrencyTo$outboundSchema: z.ZodType<
  ConversionsListOwnedCurrencyTo$Outbound,
  z.ZodTypeDef,
  ConversionsListOwnedCurrencyTo
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedCurrencyTo$ {
  /** @deprecated use `ConversionsListOwnedCurrencyTo$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedCurrencyTo$inboundSchema;
  /** @deprecated use `ConversionsListOwnedCurrencyTo$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedCurrencyTo$outboundSchema;
  /** @deprecated use `ConversionsListOwnedCurrencyTo$Outbound` instead. */
  export type Outbound = ConversionsListOwnedCurrencyTo$Outbound;
}

export function conversionsListOwnedCurrencyToToJSON(
  conversionsListOwnedCurrencyTo: ConversionsListOwnedCurrencyTo,
): string {
  return JSON.stringify(
    ConversionsListOwnedCurrencyTo$outboundSchema.parse(
      conversionsListOwnedCurrencyTo,
    ),
  );
}

export function conversionsListOwnedCurrencyToFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsListOwnedCurrencyTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsListOwnedCurrencyTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsListOwnedCurrencyTo' from JSON`,
  );
}

/** @internal */
export const ConversionsListOwnedData$inboundSchema: z.ZodType<
  ConversionsListOwnedData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  walletFromId: z.string(),
  walletToId: z.string(),
  status: ConversionsListOwnedStatus$inboundSchema,
  amountFrom: z.string(),
  amountTo: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currencyFrom: z.lazy(() => ConversionsListOwnedCurrencyFrom$inboundSchema),
  currencyTo: z.lazy(() => ConversionsListOwnedCurrencyTo$inboundSchema),
});

/** @internal */
export type ConversionsListOwnedData$Outbound = {
  id: string;
  merchantId: string;
  walletFromId: string;
  walletToId: string;
  status: string;
  amountFrom: string;
  amountTo: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currencyFrom: ConversionsListOwnedCurrencyFrom$Outbound;
  currencyTo: ConversionsListOwnedCurrencyTo$Outbound;
};

/** @internal */
export const ConversionsListOwnedData$outboundSchema: z.ZodType<
  ConversionsListOwnedData$Outbound,
  z.ZodTypeDef,
  ConversionsListOwnedData
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  walletFromId: z.string(),
  walletToId: z.string(),
  status: ConversionsListOwnedStatus$outboundSchema,
  amountFrom: z.string(),
  amountTo: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currencyFrom: z.lazy(() => ConversionsListOwnedCurrencyFrom$outboundSchema),
  currencyTo: z.lazy(() => ConversionsListOwnedCurrencyTo$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedData$ {
  /** @deprecated use `ConversionsListOwnedData$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedData$inboundSchema;
  /** @deprecated use `ConversionsListOwnedData$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedData$outboundSchema;
  /** @deprecated use `ConversionsListOwnedData$Outbound` instead. */
  export type Outbound = ConversionsListOwnedData$Outbound;
}

export function conversionsListOwnedDataToJSON(
  conversionsListOwnedData: ConversionsListOwnedData,
): string {
  return JSON.stringify(
    ConversionsListOwnedData$outboundSchema.parse(conversionsListOwnedData),
  );
}

export function conversionsListOwnedDataFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsListOwnedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsListOwnedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsListOwnedData' from JSON`,
  );
}

/** @internal */
export const ConversionsListOwnedResponse$inboundSchema: z.ZodType<
  ConversionsListOwnedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: z.lazy(() => ConversionsListOwnedMeta$inboundSchema),
  data: z.array(z.lazy(() => ConversionsListOwnedData$inboundSchema)),
});

/** @internal */
export type ConversionsListOwnedResponse$Outbound = {
  meta: ConversionsListOwnedMeta$Outbound;
  data: Array<ConversionsListOwnedData$Outbound>;
};

/** @internal */
export const ConversionsListOwnedResponse$outboundSchema: z.ZodType<
  ConversionsListOwnedResponse$Outbound,
  z.ZodTypeDef,
  ConversionsListOwnedResponse
> = z.object({
  meta: z.lazy(() => ConversionsListOwnedMeta$outboundSchema),
  data: z.array(z.lazy(() => ConversionsListOwnedData$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsListOwnedResponse$ {
  /** @deprecated use `ConversionsListOwnedResponse$inboundSchema` instead. */
  export const inboundSchema = ConversionsListOwnedResponse$inboundSchema;
  /** @deprecated use `ConversionsListOwnedResponse$outboundSchema` instead. */
  export const outboundSchema = ConversionsListOwnedResponse$outboundSchema;
  /** @deprecated use `ConversionsListOwnedResponse$Outbound` instead. */
  export type Outbound = ConversionsListOwnedResponse$Outbound;
}

export function conversionsListOwnedResponseToJSON(
  conversionsListOwnedResponse: ConversionsListOwnedResponse,
): string {
  return JSON.stringify(
    ConversionsListOwnedResponse$outboundSchema.parse(
      conversionsListOwnedResponse,
    ),
  );
}

export function conversionsListOwnedResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsListOwnedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsListOwnedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsListOwnedResponse' from JSON`,
  );
}
