/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConversionsGetByIdRequest = {
  id: string;
};

export const ConversionsGetByIdStatus = {
  Waiting: "waiting",
  Processing: "processing",
  Finished: "finished",
  Rejected: "rejected",
} as const;
export type ConversionsGetByIdStatus = ClosedEnum<
  typeof ConversionsGetByIdStatus
>;

export type ConversionsGetByIdCurrencyFrom = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ConversionsGetByIdCurrencyTo = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type ConversionsGetByIdResponse = {
  id: string;
  merchantId: string;
  walletFromId: string;
  walletToId: string;
  status: ConversionsGetByIdStatus;
  amountFrom: string;
  amountTo: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currencyFrom: ConversionsGetByIdCurrencyFrom;
  currencyTo: ConversionsGetByIdCurrencyTo;
};

/** @internal */
export const ConversionsGetByIdRequest$inboundSchema: z.ZodType<
  ConversionsGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type ConversionsGetByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const ConversionsGetByIdRequest$outboundSchema: z.ZodType<
  ConversionsGetByIdRequest$Outbound,
  z.ZodTypeDef,
  ConversionsGetByIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsGetByIdRequest$ {
  /** @deprecated use `ConversionsGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = ConversionsGetByIdRequest$inboundSchema;
  /** @deprecated use `ConversionsGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = ConversionsGetByIdRequest$outboundSchema;
  /** @deprecated use `ConversionsGetByIdRequest$Outbound` instead. */
  export type Outbound = ConversionsGetByIdRequest$Outbound;
}

export function conversionsGetByIdRequestToJSON(
  conversionsGetByIdRequest: ConversionsGetByIdRequest,
): string {
  return JSON.stringify(
    ConversionsGetByIdRequest$outboundSchema.parse(conversionsGetByIdRequest),
  );
}

export function conversionsGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsGetByIdRequest' from JSON`,
  );
}

/** @internal */
export const ConversionsGetByIdStatus$inboundSchema: z.ZodNativeEnum<
  typeof ConversionsGetByIdStatus
> = z.nativeEnum(ConversionsGetByIdStatus);

/** @internal */
export const ConversionsGetByIdStatus$outboundSchema: z.ZodNativeEnum<
  typeof ConversionsGetByIdStatus
> = ConversionsGetByIdStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsGetByIdStatus$ {
  /** @deprecated use `ConversionsGetByIdStatus$inboundSchema` instead. */
  export const inboundSchema = ConversionsGetByIdStatus$inboundSchema;
  /** @deprecated use `ConversionsGetByIdStatus$outboundSchema` instead. */
  export const outboundSchema = ConversionsGetByIdStatus$outboundSchema;
}

/** @internal */
export const ConversionsGetByIdCurrencyFrom$inboundSchema: z.ZodType<
  ConversionsGetByIdCurrencyFrom,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type ConversionsGetByIdCurrencyFrom$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const ConversionsGetByIdCurrencyFrom$outboundSchema: z.ZodType<
  ConversionsGetByIdCurrencyFrom$Outbound,
  z.ZodTypeDef,
  ConversionsGetByIdCurrencyFrom
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsGetByIdCurrencyFrom$ {
  /** @deprecated use `ConversionsGetByIdCurrencyFrom$inboundSchema` instead. */
  export const inboundSchema = ConversionsGetByIdCurrencyFrom$inboundSchema;
  /** @deprecated use `ConversionsGetByIdCurrencyFrom$outboundSchema` instead. */
  export const outboundSchema = ConversionsGetByIdCurrencyFrom$outboundSchema;
  /** @deprecated use `ConversionsGetByIdCurrencyFrom$Outbound` instead. */
  export type Outbound = ConversionsGetByIdCurrencyFrom$Outbound;
}

export function conversionsGetByIdCurrencyFromToJSON(
  conversionsGetByIdCurrencyFrom: ConversionsGetByIdCurrencyFrom,
): string {
  return JSON.stringify(
    ConversionsGetByIdCurrencyFrom$outboundSchema.parse(
      conversionsGetByIdCurrencyFrom,
    ),
  );
}

export function conversionsGetByIdCurrencyFromFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsGetByIdCurrencyFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsGetByIdCurrencyFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsGetByIdCurrencyFrom' from JSON`,
  );
}

/** @internal */
export const ConversionsGetByIdCurrencyTo$inboundSchema: z.ZodType<
  ConversionsGetByIdCurrencyTo,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type ConversionsGetByIdCurrencyTo$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const ConversionsGetByIdCurrencyTo$outboundSchema: z.ZodType<
  ConversionsGetByIdCurrencyTo$Outbound,
  z.ZodTypeDef,
  ConversionsGetByIdCurrencyTo
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsGetByIdCurrencyTo$ {
  /** @deprecated use `ConversionsGetByIdCurrencyTo$inboundSchema` instead. */
  export const inboundSchema = ConversionsGetByIdCurrencyTo$inboundSchema;
  /** @deprecated use `ConversionsGetByIdCurrencyTo$outboundSchema` instead. */
  export const outboundSchema = ConversionsGetByIdCurrencyTo$outboundSchema;
  /** @deprecated use `ConversionsGetByIdCurrencyTo$Outbound` instead. */
  export type Outbound = ConversionsGetByIdCurrencyTo$Outbound;
}

export function conversionsGetByIdCurrencyToToJSON(
  conversionsGetByIdCurrencyTo: ConversionsGetByIdCurrencyTo,
): string {
  return JSON.stringify(
    ConversionsGetByIdCurrencyTo$outboundSchema.parse(
      conversionsGetByIdCurrencyTo,
    ),
  );
}

export function conversionsGetByIdCurrencyToFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsGetByIdCurrencyTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsGetByIdCurrencyTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsGetByIdCurrencyTo' from JSON`,
  );
}

/** @internal */
export const ConversionsGetByIdResponse$inboundSchema: z.ZodType<
  ConversionsGetByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  walletFromId: z.string(),
  walletToId: z.string(),
  status: ConversionsGetByIdStatus$inboundSchema,
  amountFrom: z.string(),
  amountTo: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currencyFrom: z.lazy(() => ConversionsGetByIdCurrencyFrom$inboundSchema),
  currencyTo: z.lazy(() => ConversionsGetByIdCurrencyTo$inboundSchema),
});

/** @internal */
export type ConversionsGetByIdResponse$Outbound = {
  id: string;
  merchantId: string;
  walletFromId: string;
  walletToId: string;
  status: string;
  amountFrom: string;
  amountTo: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currencyFrom: ConversionsGetByIdCurrencyFrom$Outbound;
  currencyTo: ConversionsGetByIdCurrencyTo$Outbound;
};

/** @internal */
export const ConversionsGetByIdResponse$outboundSchema: z.ZodType<
  ConversionsGetByIdResponse$Outbound,
  z.ZodTypeDef,
  ConversionsGetByIdResponse
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  walletFromId: z.string(),
  walletToId: z.string(),
  status: ConversionsGetByIdStatus$outboundSchema,
  amountFrom: z.string(),
  amountTo: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currencyFrom: z.lazy(() => ConversionsGetByIdCurrencyFrom$outboundSchema),
  currencyTo: z.lazy(() => ConversionsGetByIdCurrencyTo$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsGetByIdResponse$ {
  /** @deprecated use `ConversionsGetByIdResponse$inboundSchema` instead. */
  export const inboundSchema = ConversionsGetByIdResponse$inboundSchema;
  /** @deprecated use `ConversionsGetByIdResponse$outboundSchema` instead. */
  export const outboundSchema = ConversionsGetByIdResponse$outboundSchema;
  /** @deprecated use `ConversionsGetByIdResponse$Outbound` instead. */
  export type Outbound = ConversionsGetByIdResponse$Outbound;
}

export function conversionsGetByIdResponseToJSON(
  conversionsGetByIdResponse: ConversionsGetByIdResponse,
): string {
  return JSON.stringify(
    ConversionsGetByIdResponse$outboundSchema.parse(conversionsGetByIdResponse),
  );
}

export function conversionsGetByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsGetByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsGetByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsGetByIdResponse' from JSON`,
  );
}
