/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Successful response
 */
export type ConversionsGetStatsResponse = {
  total: number;
  totalFromUSDAmount: number;
  totalToUSDAmount: number;
  totalWaiting: number;
  totalProcessing: number;
  totalFinished: number;
  totalRejected: number;
};

/** @internal */
export const ConversionsGetStatsResponse$inboundSchema: z.ZodType<
  ConversionsGetStatsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number(),
  totalFromUSDAmount: z.number(),
  totalToUSDAmount: z.number(),
  totalWaiting: z.number(),
  totalProcessing: z.number(),
  totalFinished: z.number(),
  totalRejected: z.number(),
});

/** @internal */
export type ConversionsGetStatsResponse$Outbound = {
  total: number;
  totalFromUSDAmount: number;
  totalToUSDAmount: number;
  totalWaiting: number;
  totalProcessing: number;
  totalFinished: number;
  totalRejected: number;
};

/** @internal */
export const ConversionsGetStatsResponse$outboundSchema: z.ZodType<
  ConversionsGetStatsResponse$Outbound,
  z.ZodTypeDef,
  ConversionsGetStatsResponse
> = z.object({
  total: z.number(),
  totalFromUSDAmount: z.number(),
  totalToUSDAmount: z.number(),
  totalWaiting: z.number(),
  totalProcessing: z.number(),
  totalFinished: z.number(),
  totalRejected: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsGetStatsResponse$ {
  /** @deprecated use `ConversionsGetStatsResponse$inboundSchema` instead. */
  export const inboundSchema = ConversionsGetStatsResponse$inboundSchema;
  /** @deprecated use `ConversionsGetStatsResponse$outboundSchema` instead. */
  export const outboundSchema = ConversionsGetStatsResponse$outboundSchema;
  /** @deprecated use `ConversionsGetStatsResponse$Outbound` instead. */
  export type Outbound = ConversionsGetStatsResponse$Outbound;
}

export function conversionsGetStatsResponseToJSON(
  conversionsGetStatsResponse: ConversionsGetStatsResponse,
): string {
  return JSON.stringify(
    ConversionsGetStatsResponse$outboundSchema.parse(
      conversionsGetStatsResponse,
    ),
  );
}

export function conversionsGetStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsGetStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsGetStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsGetStatsResponse' from JSON`,
  );
}
