/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConversionsCreateRequest = {
  amountFrom: string;
  callbackUrl?: string | null | undefined;
  currencyFrom: string;
  currencyTo: string;
};

export const ConversionsCreateStatus = {
  Waiting: "waiting",
  Processing: "processing",
  Finished: "finished",
  Rejected: "rejected",
} as const;
export type ConversionsCreateStatus = ClosedEnum<
  typeof ConversionsCreateStatus
>;

export type ConversionsCreateCurrencyFrom = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ConversionsCreateCurrencyTo = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type ConversionsCreateResponse = {
  id: string;
  merchantId: string;
  walletFromId: string;
  walletToId: string;
  status: ConversionsCreateStatus;
  amountFrom: string;
  amountTo: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currencyFrom: ConversionsCreateCurrencyFrom;
  currencyTo: ConversionsCreateCurrencyTo;
};

/** @internal */
export const ConversionsCreateRequest$inboundSchema: z.ZodType<
  ConversionsCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  amountFrom: z.string(),
  callbackUrl: z.nullable(z.string()).optional(),
  currencyFrom: z.string(),
  currencyTo: z.string(),
});

/** @internal */
export type ConversionsCreateRequest$Outbound = {
  amountFrom: string;
  callbackUrl?: string | null | undefined;
  currencyFrom: string;
  currencyTo: string;
};

/** @internal */
export const ConversionsCreateRequest$outboundSchema: z.ZodType<
  ConversionsCreateRequest$Outbound,
  z.ZodTypeDef,
  ConversionsCreateRequest
> = z.object({
  amountFrom: z.string(),
  callbackUrl: z.nullable(z.string()).optional(),
  currencyFrom: z.string(),
  currencyTo: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsCreateRequest$ {
  /** @deprecated use `ConversionsCreateRequest$inboundSchema` instead. */
  export const inboundSchema = ConversionsCreateRequest$inboundSchema;
  /** @deprecated use `ConversionsCreateRequest$outboundSchema` instead. */
  export const outboundSchema = ConversionsCreateRequest$outboundSchema;
  /** @deprecated use `ConversionsCreateRequest$Outbound` instead. */
  export type Outbound = ConversionsCreateRequest$Outbound;
}

export function conversionsCreateRequestToJSON(
  conversionsCreateRequest: ConversionsCreateRequest,
): string {
  return JSON.stringify(
    ConversionsCreateRequest$outboundSchema.parse(conversionsCreateRequest),
  );
}

export function conversionsCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsCreateRequest' from JSON`,
  );
}

/** @internal */
export const ConversionsCreateStatus$inboundSchema: z.ZodNativeEnum<
  typeof ConversionsCreateStatus
> = z.nativeEnum(ConversionsCreateStatus);

/** @internal */
export const ConversionsCreateStatus$outboundSchema: z.ZodNativeEnum<
  typeof ConversionsCreateStatus
> = ConversionsCreateStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsCreateStatus$ {
  /** @deprecated use `ConversionsCreateStatus$inboundSchema` instead. */
  export const inboundSchema = ConversionsCreateStatus$inboundSchema;
  /** @deprecated use `ConversionsCreateStatus$outboundSchema` instead. */
  export const outboundSchema = ConversionsCreateStatus$outboundSchema;
}

/** @internal */
export const ConversionsCreateCurrencyFrom$inboundSchema: z.ZodType<
  ConversionsCreateCurrencyFrom,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type ConversionsCreateCurrencyFrom$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const ConversionsCreateCurrencyFrom$outboundSchema: z.ZodType<
  ConversionsCreateCurrencyFrom$Outbound,
  z.ZodTypeDef,
  ConversionsCreateCurrencyFrom
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsCreateCurrencyFrom$ {
  /** @deprecated use `ConversionsCreateCurrencyFrom$inboundSchema` instead. */
  export const inboundSchema = ConversionsCreateCurrencyFrom$inboundSchema;
  /** @deprecated use `ConversionsCreateCurrencyFrom$outboundSchema` instead. */
  export const outboundSchema = ConversionsCreateCurrencyFrom$outboundSchema;
  /** @deprecated use `ConversionsCreateCurrencyFrom$Outbound` instead. */
  export type Outbound = ConversionsCreateCurrencyFrom$Outbound;
}

export function conversionsCreateCurrencyFromToJSON(
  conversionsCreateCurrencyFrom: ConversionsCreateCurrencyFrom,
): string {
  return JSON.stringify(
    ConversionsCreateCurrencyFrom$outboundSchema.parse(
      conversionsCreateCurrencyFrom,
    ),
  );
}

export function conversionsCreateCurrencyFromFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsCreateCurrencyFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsCreateCurrencyFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsCreateCurrencyFrom' from JSON`,
  );
}

/** @internal */
export const ConversionsCreateCurrencyTo$inboundSchema: z.ZodType<
  ConversionsCreateCurrencyTo,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type ConversionsCreateCurrencyTo$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const ConversionsCreateCurrencyTo$outboundSchema: z.ZodType<
  ConversionsCreateCurrencyTo$Outbound,
  z.ZodTypeDef,
  ConversionsCreateCurrencyTo
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsCreateCurrencyTo$ {
  /** @deprecated use `ConversionsCreateCurrencyTo$inboundSchema` instead. */
  export const inboundSchema = ConversionsCreateCurrencyTo$inboundSchema;
  /** @deprecated use `ConversionsCreateCurrencyTo$outboundSchema` instead. */
  export const outboundSchema = ConversionsCreateCurrencyTo$outboundSchema;
  /** @deprecated use `ConversionsCreateCurrencyTo$Outbound` instead. */
  export type Outbound = ConversionsCreateCurrencyTo$Outbound;
}

export function conversionsCreateCurrencyToToJSON(
  conversionsCreateCurrencyTo: ConversionsCreateCurrencyTo,
): string {
  return JSON.stringify(
    ConversionsCreateCurrencyTo$outboundSchema.parse(
      conversionsCreateCurrencyTo,
    ),
  );
}

export function conversionsCreateCurrencyToFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsCreateCurrencyTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsCreateCurrencyTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsCreateCurrencyTo' from JSON`,
  );
}

/** @internal */
export const ConversionsCreateResponse$inboundSchema: z.ZodType<
  ConversionsCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  walletFromId: z.string(),
  walletToId: z.string(),
  status: ConversionsCreateStatus$inboundSchema,
  amountFrom: z.string(),
  amountTo: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currencyFrom: z.lazy(() => ConversionsCreateCurrencyFrom$inboundSchema),
  currencyTo: z.lazy(() => ConversionsCreateCurrencyTo$inboundSchema),
});

/** @internal */
export type ConversionsCreateResponse$Outbound = {
  id: string;
  merchantId: string;
  walletFromId: string;
  walletToId: string;
  status: string;
  amountFrom: string;
  amountTo: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currencyFrom: ConversionsCreateCurrencyFrom$Outbound;
  currencyTo: ConversionsCreateCurrencyTo$Outbound;
};

/** @internal */
export const ConversionsCreateResponse$outboundSchema: z.ZodType<
  ConversionsCreateResponse$Outbound,
  z.ZodTypeDef,
  ConversionsCreateResponse
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  walletFromId: z.string(),
  walletToId: z.string(),
  status: ConversionsCreateStatus$outboundSchema,
  amountFrom: z.string(),
  amountTo: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currencyFrom: z.lazy(() => ConversionsCreateCurrencyFrom$outboundSchema),
  currencyTo: z.lazy(() => ConversionsCreateCurrencyTo$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversionsCreateResponse$ {
  /** @deprecated use `ConversionsCreateResponse$inboundSchema` instead. */
  export const inboundSchema = ConversionsCreateResponse$inboundSchema;
  /** @deprecated use `ConversionsCreateResponse$outboundSchema` instead. */
  export const outboundSchema = ConversionsCreateResponse$outboundSchema;
  /** @deprecated use `ConversionsCreateResponse$Outbound` instead. */
  export type Outbound = ConversionsCreateResponse$Outbound;
}

export function conversionsCreateResponseToJSON(
  conversionsCreateResponse: ConversionsCreateResponse,
): string {
  return JSON.stringify(
    ConversionsCreateResponse$outboundSchema.parse(conversionsCreateResponse),
  );
}

export function conversionsCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConversionsCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionsCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionsCreateResponse' from JSON`,
  );
}
