/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PaymentInvoicesListOwnedFilter = {
  createdStart?: string | null | undefined;
  createdEnd?: string | null | undefined;
  merchants?: Array<string> | null | undefined;
  q?: string | null | undefined;
};

export type PaymentInvoicesListOwnedRequest = {
  filter?: PaymentInvoicesListOwnedFilter | undefined;
  sort?: Array<string> | null | undefined;
  cursor?: string | undefined;
  pageSize?: number | undefined;
};

export type PaymentInvoicesListOwnedCursor = string | any;

export type PaymentInvoicesListOwnedMeta = {
  cursor?: string | any | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

export const PaymentInvoicesListOwnedStatus = {
  Waiting: "waiting",
  Confirming: "confirming",
  Confirmed: "confirmed",
  Sending: "sending",
  PartiallyPaid: "partially_paid",
  Finished: "finished",
  Failed: "failed",
  Expired: "expired",
} as const;
export type PaymentInvoicesListOwnedStatus = ClosedEnum<
  typeof PaymentInvoicesListOwnedStatus
>;

export type PaymentInvoicesListOwnedPayCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PaymentInvoicesListOwnedAcceptedCoin = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PaymentInvoicesListOwnedData = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: PaymentInvoicesListOwnedStatus;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  returnUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PaymentInvoicesListOwnedPayCurrency | null;
  acceptedCoins: Array<PaymentInvoicesListOwnedAcceptedCoin>;
};

/**
 * Successful response
 */
export type PaymentInvoicesListOwnedResponse = {
  meta: PaymentInvoicesListOwnedMeta;
  data: Array<PaymentInvoicesListOwnedData>;
};

/** @internal */
export const PaymentInvoicesListOwnedFilter$inboundSchema: z.ZodType<
  PaymentInvoicesListOwnedFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_start: z.nullable(z.string()).optional(),
  created_end: z.nullable(z.string()).optional(),
  merchants: z.nullable(z.array(z.string())).optional(),
  q: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_start": "createdStart",
    "created_end": "createdEnd",
  });
});

/** @internal */
export type PaymentInvoicesListOwnedFilter$Outbound = {
  created_start?: string | null | undefined;
  created_end?: string | null | undefined;
  merchants?: Array<string> | null | undefined;
  q?: string | null | undefined;
};

/** @internal */
export const PaymentInvoicesListOwnedFilter$outboundSchema: z.ZodType<
  PaymentInvoicesListOwnedFilter$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesListOwnedFilter
> = z.object({
  createdStart: z.nullable(z.string()).optional(),
  createdEnd: z.nullable(z.string()).optional(),
  merchants: z.nullable(z.array(z.string())).optional(),
  q: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    createdStart: "created_start",
    createdEnd: "created_end",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedFilter$ {
  /** @deprecated use `PaymentInvoicesListOwnedFilter$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesListOwnedFilter$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedFilter$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesListOwnedFilter$outboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedFilter$Outbound` instead. */
  export type Outbound = PaymentInvoicesListOwnedFilter$Outbound;
}

export function paymentInvoicesListOwnedFilterToJSON(
  paymentInvoicesListOwnedFilter: PaymentInvoicesListOwnedFilter,
): string {
  return JSON.stringify(
    PaymentInvoicesListOwnedFilter$outboundSchema.parse(
      paymentInvoicesListOwnedFilter,
    ),
  );
}

export function paymentInvoicesListOwnedFilterFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesListOwnedFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesListOwnedFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesListOwnedFilter' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesListOwnedRequest$inboundSchema: z.ZodType<
  PaymentInvoicesListOwnedRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filter: z.lazy(() => PaymentInvoicesListOwnedFilter$inboundSchema).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  cursor: z.string().optional(),
  pageSize: z.number().optional(),
});

/** @internal */
export type PaymentInvoicesListOwnedRequest$Outbound = {
  filter?: PaymentInvoicesListOwnedFilter$Outbound | undefined;
  sort?: Array<string> | null | undefined;
  cursor?: string | undefined;
  pageSize?: number | undefined;
};

/** @internal */
export const PaymentInvoicesListOwnedRequest$outboundSchema: z.ZodType<
  PaymentInvoicesListOwnedRequest$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesListOwnedRequest
> = z.object({
  filter: z.lazy(() => PaymentInvoicesListOwnedFilter$outboundSchema)
    .optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  cursor: z.string().optional(),
  pageSize: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedRequest$ {
  /** @deprecated use `PaymentInvoicesListOwnedRequest$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesListOwnedRequest$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedRequest$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesListOwnedRequest$outboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedRequest$Outbound` instead. */
  export type Outbound = PaymentInvoicesListOwnedRequest$Outbound;
}

export function paymentInvoicesListOwnedRequestToJSON(
  paymentInvoicesListOwnedRequest: PaymentInvoicesListOwnedRequest,
): string {
  return JSON.stringify(
    PaymentInvoicesListOwnedRequest$outboundSchema.parse(
      paymentInvoicesListOwnedRequest,
    ),
  );
}

export function paymentInvoicesListOwnedRequestFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesListOwnedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesListOwnedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesListOwnedRequest' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesListOwnedCursor$inboundSchema: z.ZodType<
  PaymentInvoicesListOwnedCursor,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.any()]);

/** @internal */
export type PaymentInvoicesListOwnedCursor$Outbound = string | any;

/** @internal */
export const PaymentInvoicesListOwnedCursor$outboundSchema: z.ZodType<
  PaymentInvoicesListOwnedCursor$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesListOwnedCursor
> = z.union([z.string(), z.any()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedCursor$ {
  /** @deprecated use `PaymentInvoicesListOwnedCursor$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesListOwnedCursor$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedCursor$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesListOwnedCursor$outboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedCursor$Outbound` instead. */
  export type Outbound = PaymentInvoicesListOwnedCursor$Outbound;
}

export function paymentInvoicesListOwnedCursorToJSON(
  paymentInvoicesListOwnedCursor: PaymentInvoicesListOwnedCursor,
): string {
  return JSON.stringify(
    PaymentInvoicesListOwnedCursor$outboundSchema.parse(
      paymentInvoicesListOwnedCursor,
    ),
  );
}

export function paymentInvoicesListOwnedCursorFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesListOwnedCursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesListOwnedCursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesListOwnedCursor' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesListOwnedMeta$inboundSchema: z.ZodType<
  PaymentInvoicesListOwnedMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.union([z.string(), z.any()]).optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/** @internal */
export type PaymentInvoicesListOwnedMeta$Outbound = {
  cursor?: string | any | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/** @internal */
export const PaymentInvoicesListOwnedMeta$outboundSchema: z.ZodType<
  PaymentInvoicesListOwnedMeta$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesListOwnedMeta
> = z.object({
  cursor: z.union([z.string(), z.any()]).optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedMeta$ {
  /** @deprecated use `PaymentInvoicesListOwnedMeta$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesListOwnedMeta$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedMeta$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesListOwnedMeta$outboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedMeta$Outbound` instead. */
  export type Outbound = PaymentInvoicesListOwnedMeta$Outbound;
}

export function paymentInvoicesListOwnedMetaToJSON(
  paymentInvoicesListOwnedMeta: PaymentInvoicesListOwnedMeta,
): string {
  return JSON.stringify(
    PaymentInvoicesListOwnedMeta$outboundSchema.parse(
      paymentInvoicesListOwnedMeta,
    ),
  );
}

export function paymentInvoicesListOwnedMetaFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesListOwnedMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesListOwnedMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesListOwnedMeta' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesListOwnedStatus$inboundSchema: z.ZodNativeEnum<
  typeof PaymentInvoicesListOwnedStatus
> = z.nativeEnum(PaymentInvoicesListOwnedStatus);

/** @internal */
export const PaymentInvoicesListOwnedStatus$outboundSchema: z.ZodNativeEnum<
  typeof PaymentInvoicesListOwnedStatus
> = PaymentInvoicesListOwnedStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedStatus$ {
  /** @deprecated use `PaymentInvoicesListOwnedStatus$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesListOwnedStatus$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedStatus$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesListOwnedStatus$outboundSchema;
}

/** @internal */
export const PaymentInvoicesListOwnedPayCurrency$inboundSchema: z.ZodType<
  PaymentInvoicesListOwnedPayCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PaymentInvoicesListOwnedPayCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PaymentInvoicesListOwnedPayCurrency$outboundSchema: z.ZodType<
  PaymentInvoicesListOwnedPayCurrency$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesListOwnedPayCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedPayCurrency$ {
  /** @deprecated use `PaymentInvoicesListOwnedPayCurrency$inboundSchema` instead. */
  export const inboundSchema =
    PaymentInvoicesListOwnedPayCurrency$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedPayCurrency$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesListOwnedPayCurrency$outboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedPayCurrency$Outbound` instead. */
  export type Outbound = PaymentInvoicesListOwnedPayCurrency$Outbound;
}

export function paymentInvoicesListOwnedPayCurrencyToJSON(
  paymentInvoicesListOwnedPayCurrency: PaymentInvoicesListOwnedPayCurrency,
): string {
  return JSON.stringify(
    PaymentInvoicesListOwnedPayCurrency$outboundSchema.parse(
      paymentInvoicesListOwnedPayCurrency,
    ),
  );
}

export function paymentInvoicesListOwnedPayCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesListOwnedPayCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaymentInvoicesListOwnedPayCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesListOwnedPayCurrency' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesListOwnedAcceptedCoin$inboundSchema: z.ZodType<
  PaymentInvoicesListOwnedAcceptedCoin,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PaymentInvoicesListOwnedAcceptedCoin$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PaymentInvoicesListOwnedAcceptedCoin$outboundSchema: z.ZodType<
  PaymentInvoicesListOwnedAcceptedCoin$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesListOwnedAcceptedCoin
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedAcceptedCoin$ {
  /** @deprecated use `PaymentInvoicesListOwnedAcceptedCoin$inboundSchema` instead. */
  export const inboundSchema =
    PaymentInvoicesListOwnedAcceptedCoin$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedAcceptedCoin$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesListOwnedAcceptedCoin$outboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedAcceptedCoin$Outbound` instead. */
  export type Outbound = PaymentInvoicesListOwnedAcceptedCoin$Outbound;
}

export function paymentInvoicesListOwnedAcceptedCoinToJSON(
  paymentInvoicesListOwnedAcceptedCoin: PaymentInvoicesListOwnedAcceptedCoin,
): string {
  return JSON.stringify(
    PaymentInvoicesListOwnedAcceptedCoin$outboundSchema.parse(
      paymentInvoicesListOwnedAcceptedCoin,
    ),
  );
}

export function paymentInvoicesListOwnedAcceptedCoinFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesListOwnedAcceptedCoin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaymentInvoicesListOwnedAcceptedCoin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesListOwnedAcceptedCoin' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesListOwnedData$inboundSchema: z.ZodType<
  PaymentInvoicesListOwnedData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PaymentInvoicesListOwnedStatus$inboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  returnUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PaymentInvoicesListOwnedPayCurrency$inboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PaymentInvoicesListOwnedAcceptedCoin$inboundSchema),
  ),
});

/** @internal */
export type PaymentInvoicesListOwnedData$Outbound = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: string;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  returnUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PaymentInvoicesListOwnedPayCurrency$Outbound | null;
  acceptedCoins: Array<PaymentInvoicesListOwnedAcceptedCoin$Outbound>;
};

/** @internal */
export const PaymentInvoicesListOwnedData$outboundSchema: z.ZodType<
  PaymentInvoicesListOwnedData$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesListOwnedData
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PaymentInvoicesListOwnedStatus$outboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  returnUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PaymentInvoicesListOwnedPayCurrency$outboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PaymentInvoicesListOwnedAcceptedCoin$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedData$ {
  /** @deprecated use `PaymentInvoicesListOwnedData$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesListOwnedData$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedData$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesListOwnedData$outboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedData$Outbound` instead. */
  export type Outbound = PaymentInvoicesListOwnedData$Outbound;
}

export function paymentInvoicesListOwnedDataToJSON(
  paymentInvoicesListOwnedData: PaymentInvoicesListOwnedData,
): string {
  return JSON.stringify(
    PaymentInvoicesListOwnedData$outboundSchema.parse(
      paymentInvoicesListOwnedData,
    ),
  );
}

export function paymentInvoicesListOwnedDataFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesListOwnedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesListOwnedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesListOwnedData' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesListOwnedResponse$inboundSchema: z.ZodType<
  PaymentInvoicesListOwnedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: z.lazy(() => PaymentInvoicesListOwnedMeta$inboundSchema),
  data: z.array(z.lazy(() => PaymentInvoicesListOwnedData$inboundSchema)),
});

/** @internal */
export type PaymentInvoicesListOwnedResponse$Outbound = {
  meta: PaymentInvoicesListOwnedMeta$Outbound;
  data: Array<PaymentInvoicesListOwnedData$Outbound>;
};

/** @internal */
export const PaymentInvoicesListOwnedResponse$outboundSchema: z.ZodType<
  PaymentInvoicesListOwnedResponse$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesListOwnedResponse
> = z.object({
  meta: z.lazy(() => PaymentInvoicesListOwnedMeta$outboundSchema),
  data: z.array(z.lazy(() => PaymentInvoicesListOwnedData$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesListOwnedResponse$ {
  /** @deprecated use `PaymentInvoicesListOwnedResponse$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesListOwnedResponse$inboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedResponse$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesListOwnedResponse$outboundSchema;
  /** @deprecated use `PaymentInvoicesListOwnedResponse$Outbound` instead. */
  export type Outbound = PaymentInvoicesListOwnedResponse$Outbound;
}

export function paymentInvoicesListOwnedResponseToJSON(
  paymentInvoicesListOwnedResponse: PaymentInvoicesListOwnedResponse,
): string {
  return JSON.stringify(
    PaymentInvoicesListOwnedResponse$outboundSchema.parse(
      paymentInvoicesListOwnedResponse,
    ),
  );
}

export function paymentInvoicesListOwnedResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesListOwnedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesListOwnedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesListOwnedResponse' from JSON`,
  );
}
