/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PaymentInvoicesGetByIdRequest = {
  id: string;
};

export const PaymentInvoicesGetByIdStatus = {
  Waiting: "waiting",
  Confirming: "confirming",
  Confirmed: "confirmed",
  Sending: "sending",
  PartiallyPaid: "partially_paid",
  Finished: "finished",
  Failed: "failed",
  Expired: "expired",
} as const;
export type PaymentInvoicesGetByIdStatus = ClosedEnum<
  typeof PaymentInvoicesGetByIdStatus
>;

export type PaymentInvoicesGetByIdPayCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PaymentInvoicesGetByIdAcceptedCoin = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type PaymentInvoicesGetByIdResponse = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: PaymentInvoicesGetByIdStatus;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  returnUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PaymentInvoicesGetByIdPayCurrency | null;
  acceptedCoins: Array<PaymentInvoicesGetByIdAcceptedCoin>;
  paymentUrl: string;
};

/** @internal */
export const PaymentInvoicesGetByIdRequest$inboundSchema: z.ZodType<
  PaymentInvoicesGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type PaymentInvoicesGetByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const PaymentInvoicesGetByIdRequest$outboundSchema: z.ZodType<
  PaymentInvoicesGetByIdRequest$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesGetByIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesGetByIdRequest$ {
  /** @deprecated use `PaymentInvoicesGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesGetByIdRequest$inboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesGetByIdRequest$outboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdRequest$Outbound` instead. */
  export type Outbound = PaymentInvoicesGetByIdRequest$Outbound;
}

export function paymentInvoicesGetByIdRequestToJSON(
  paymentInvoicesGetByIdRequest: PaymentInvoicesGetByIdRequest,
): string {
  return JSON.stringify(
    PaymentInvoicesGetByIdRequest$outboundSchema.parse(
      paymentInvoicesGetByIdRequest,
    ),
  );
}

export function paymentInvoicesGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesGetByIdRequest' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesGetByIdStatus$inboundSchema: z.ZodNativeEnum<
  typeof PaymentInvoicesGetByIdStatus
> = z.nativeEnum(PaymentInvoicesGetByIdStatus);

/** @internal */
export const PaymentInvoicesGetByIdStatus$outboundSchema: z.ZodNativeEnum<
  typeof PaymentInvoicesGetByIdStatus
> = PaymentInvoicesGetByIdStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesGetByIdStatus$ {
  /** @deprecated use `PaymentInvoicesGetByIdStatus$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesGetByIdStatus$inboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdStatus$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesGetByIdStatus$outboundSchema;
}

/** @internal */
export const PaymentInvoicesGetByIdPayCurrency$inboundSchema: z.ZodType<
  PaymentInvoicesGetByIdPayCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PaymentInvoicesGetByIdPayCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PaymentInvoicesGetByIdPayCurrency$outboundSchema: z.ZodType<
  PaymentInvoicesGetByIdPayCurrency$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesGetByIdPayCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesGetByIdPayCurrency$ {
  /** @deprecated use `PaymentInvoicesGetByIdPayCurrency$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesGetByIdPayCurrency$inboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdPayCurrency$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesGetByIdPayCurrency$outboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdPayCurrency$Outbound` instead. */
  export type Outbound = PaymentInvoicesGetByIdPayCurrency$Outbound;
}

export function paymentInvoicesGetByIdPayCurrencyToJSON(
  paymentInvoicesGetByIdPayCurrency: PaymentInvoicesGetByIdPayCurrency,
): string {
  return JSON.stringify(
    PaymentInvoicesGetByIdPayCurrency$outboundSchema.parse(
      paymentInvoicesGetByIdPayCurrency,
    ),
  );
}

export function paymentInvoicesGetByIdPayCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesGetByIdPayCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesGetByIdPayCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesGetByIdPayCurrency' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesGetByIdAcceptedCoin$inboundSchema: z.ZodType<
  PaymentInvoicesGetByIdAcceptedCoin,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PaymentInvoicesGetByIdAcceptedCoin$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PaymentInvoicesGetByIdAcceptedCoin$outboundSchema: z.ZodType<
  PaymentInvoicesGetByIdAcceptedCoin$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesGetByIdAcceptedCoin
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesGetByIdAcceptedCoin$ {
  /** @deprecated use `PaymentInvoicesGetByIdAcceptedCoin$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesGetByIdAcceptedCoin$inboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdAcceptedCoin$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesGetByIdAcceptedCoin$outboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdAcceptedCoin$Outbound` instead. */
  export type Outbound = PaymentInvoicesGetByIdAcceptedCoin$Outbound;
}

export function paymentInvoicesGetByIdAcceptedCoinToJSON(
  paymentInvoicesGetByIdAcceptedCoin: PaymentInvoicesGetByIdAcceptedCoin,
): string {
  return JSON.stringify(
    PaymentInvoicesGetByIdAcceptedCoin$outboundSchema.parse(
      paymentInvoicesGetByIdAcceptedCoin,
    ),
  );
}

export function paymentInvoicesGetByIdAcceptedCoinFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesGetByIdAcceptedCoin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaymentInvoicesGetByIdAcceptedCoin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesGetByIdAcceptedCoin' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesGetByIdResponse$inboundSchema: z.ZodType<
  PaymentInvoicesGetByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PaymentInvoicesGetByIdStatus$inboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  returnUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PaymentInvoicesGetByIdPayCurrency$inboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PaymentInvoicesGetByIdAcceptedCoin$inboundSchema),
  ),
  paymentUrl: z.string(),
});

/** @internal */
export type PaymentInvoicesGetByIdResponse$Outbound = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: string;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  returnUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PaymentInvoicesGetByIdPayCurrency$Outbound | null;
  acceptedCoins: Array<PaymentInvoicesGetByIdAcceptedCoin$Outbound>;
  paymentUrl: string;
};

/** @internal */
export const PaymentInvoicesGetByIdResponse$outboundSchema: z.ZodType<
  PaymentInvoicesGetByIdResponse$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesGetByIdResponse
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PaymentInvoicesGetByIdStatus$outboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  returnUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PaymentInvoicesGetByIdPayCurrency$outboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PaymentInvoicesGetByIdAcceptedCoin$outboundSchema),
  ),
  paymentUrl: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesGetByIdResponse$ {
  /** @deprecated use `PaymentInvoicesGetByIdResponse$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesGetByIdResponse$inboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdResponse$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesGetByIdResponse$outboundSchema;
  /** @deprecated use `PaymentInvoicesGetByIdResponse$Outbound` instead. */
  export type Outbound = PaymentInvoicesGetByIdResponse$Outbound;
}

export function paymentInvoicesGetByIdResponseToJSON(
  paymentInvoicesGetByIdResponse: PaymentInvoicesGetByIdResponse,
): string {
  return JSON.stringify(
    PaymentInvoicesGetByIdResponse$outboundSchema.parse(
      paymentInvoicesGetByIdResponse,
    ),
  );
}

export function paymentInvoicesGetByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesGetByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesGetByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesGetByIdResponse' from JSON`,
  );
}
