/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Successful response
 */
export type PaymentInvoicesGetStatsResponse = {
  total: number;
  totalUSDVolume: number;
  totalFinished: number;
};

/** @internal */
export const PaymentInvoicesGetStatsResponse$inboundSchema: z.ZodType<
  PaymentInvoicesGetStatsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number(),
  totalUSDVolume: z.number(),
  totalFinished: z.number(),
});

/** @internal */
export type PaymentInvoicesGetStatsResponse$Outbound = {
  total: number;
  totalUSDVolume: number;
  totalFinished: number;
};

/** @internal */
export const PaymentInvoicesGetStatsResponse$outboundSchema: z.ZodType<
  PaymentInvoicesGetStatsResponse$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesGetStatsResponse
> = z.object({
  total: z.number(),
  totalUSDVolume: z.number(),
  totalFinished: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesGetStatsResponse$ {
  /** @deprecated use `PaymentInvoicesGetStatsResponse$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesGetStatsResponse$inboundSchema;
  /** @deprecated use `PaymentInvoicesGetStatsResponse$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesGetStatsResponse$outboundSchema;
  /** @deprecated use `PaymentInvoicesGetStatsResponse$Outbound` instead. */
  export type Outbound = PaymentInvoicesGetStatsResponse$Outbound;
}

export function paymentInvoicesGetStatsResponseToJSON(
  paymentInvoicesGetStatsResponse: PaymentInvoicesGetStatsResponse,
): string {
  return JSON.stringify(
    PaymentInvoicesGetStatsResponse$outboundSchema.parse(
      paymentInvoicesGetStatsResponse,
    ),
  );
}

export function paymentInvoicesGetStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesGetStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesGetStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesGetStatsResponse' from JSON`,
  );
}
