/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PaymentInvoicesCreateRequest = {
  feePaidByPayer?: boolean | undefined;
  callbackUrl?: string | null | undefined;
  amount: number;
  amountCurrency?: string | undefined;
  underPaidCover?: number | undefined;
  lifeTime?: number | undefined;
  acceptedCoins?: Array<string> | undefined;
  returnUrl?: string | null | undefined;
};

export const PaymentInvoicesCreateStatus = {
  Waiting: "waiting",
  Confirming: "confirming",
  Confirmed: "confirmed",
  Sending: "sending",
  PartiallyPaid: "partially_paid",
  Finished: "finished",
  Failed: "failed",
  Expired: "expired",
} as const;
export type PaymentInvoicesCreateStatus = ClosedEnum<
  typeof PaymentInvoicesCreateStatus
>;

export type PaymentInvoicesCreatePayCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PaymentInvoicesCreateAcceptedCoin = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type PaymentInvoicesCreateResponse = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: PaymentInvoicesCreateStatus;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  returnUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PaymentInvoicesCreatePayCurrency | null;
  acceptedCoins: Array<PaymentInvoicesCreateAcceptedCoin>;
  paymentUrl: string;
};

/** @internal */
export const PaymentInvoicesCreateRequest$inboundSchema: z.ZodType<
  PaymentInvoicesCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  feePaidByPayer: z.boolean().optional(),
  callbackUrl: z.nullable(z.string()).optional(),
  amount: z.number(),
  amountCurrency: z.string().default("USD"),
  underPaidCover: z.number().optional(),
  lifeTime: z.number().default(10080),
  acceptedCoins: z.array(z.string()).optional(),
  returnUrl: z.nullable(z.string()).optional(),
});

/** @internal */
export type PaymentInvoicesCreateRequest$Outbound = {
  feePaidByPayer?: boolean | undefined;
  callbackUrl?: string | null | undefined;
  amount: number;
  amountCurrency: string;
  underPaidCover?: number | undefined;
  lifeTime: number;
  acceptedCoins?: Array<string> | undefined;
  returnUrl?: string | null | undefined;
};

/** @internal */
export const PaymentInvoicesCreateRequest$outboundSchema: z.ZodType<
  PaymentInvoicesCreateRequest$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesCreateRequest
> = z.object({
  feePaidByPayer: z.boolean().optional(),
  callbackUrl: z.nullable(z.string()).optional(),
  amount: z.number(),
  amountCurrency: z.string().default("USD"),
  underPaidCover: z.number().optional(),
  lifeTime: z.number().default(10080),
  acceptedCoins: z.array(z.string()).optional(),
  returnUrl: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateRequest$ {
  /** @deprecated use `PaymentInvoicesCreateRequest$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesCreateRequest$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateRequest$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesCreateRequest$outboundSchema;
  /** @deprecated use `PaymentInvoicesCreateRequest$Outbound` instead. */
  export type Outbound = PaymentInvoicesCreateRequest$Outbound;
}

export function paymentInvoicesCreateRequestToJSON(
  paymentInvoicesCreateRequest: PaymentInvoicesCreateRequest,
): string {
  return JSON.stringify(
    PaymentInvoicesCreateRequest$outboundSchema.parse(
      paymentInvoicesCreateRequest,
    ),
  );
}

export function paymentInvoicesCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesCreateRequest' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesCreateStatus$inboundSchema: z.ZodNativeEnum<
  typeof PaymentInvoicesCreateStatus
> = z.nativeEnum(PaymentInvoicesCreateStatus);

/** @internal */
export const PaymentInvoicesCreateStatus$outboundSchema: z.ZodNativeEnum<
  typeof PaymentInvoicesCreateStatus
> = PaymentInvoicesCreateStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateStatus$ {
  /** @deprecated use `PaymentInvoicesCreateStatus$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesCreateStatus$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateStatus$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesCreateStatus$outboundSchema;
}

/** @internal */
export const PaymentInvoicesCreatePayCurrency$inboundSchema: z.ZodType<
  PaymentInvoicesCreatePayCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PaymentInvoicesCreatePayCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PaymentInvoicesCreatePayCurrency$outboundSchema: z.ZodType<
  PaymentInvoicesCreatePayCurrency$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesCreatePayCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreatePayCurrency$ {
  /** @deprecated use `PaymentInvoicesCreatePayCurrency$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesCreatePayCurrency$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreatePayCurrency$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesCreatePayCurrency$outboundSchema;
  /** @deprecated use `PaymentInvoicesCreatePayCurrency$Outbound` instead. */
  export type Outbound = PaymentInvoicesCreatePayCurrency$Outbound;
}

export function paymentInvoicesCreatePayCurrencyToJSON(
  paymentInvoicesCreatePayCurrency: PaymentInvoicesCreatePayCurrency,
): string {
  return JSON.stringify(
    PaymentInvoicesCreatePayCurrency$outboundSchema.parse(
      paymentInvoicesCreatePayCurrency,
    ),
  );
}

export function paymentInvoicesCreatePayCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesCreatePayCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesCreatePayCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesCreatePayCurrency' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesCreateAcceptedCoin$inboundSchema: z.ZodType<
  PaymentInvoicesCreateAcceptedCoin,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PaymentInvoicesCreateAcceptedCoin$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PaymentInvoicesCreateAcceptedCoin$outboundSchema: z.ZodType<
  PaymentInvoicesCreateAcceptedCoin$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesCreateAcceptedCoin
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateAcceptedCoin$ {
  /** @deprecated use `PaymentInvoicesCreateAcceptedCoin$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesCreateAcceptedCoin$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateAcceptedCoin$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesCreateAcceptedCoin$outboundSchema;
  /** @deprecated use `PaymentInvoicesCreateAcceptedCoin$Outbound` instead. */
  export type Outbound = PaymentInvoicesCreateAcceptedCoin$Outbound;
}

export function paymentInvoicesCreateAcceptedCoinToJSON(
  paymentInvoicesCreateAcceptedCoin: PaymentInvoicesCreateAcceptedCoin,
): string {
  return JSON.stringify(
    PaymentInvoicesCreateAcceptedCoin$outboundSchema.parse(
      paymentInvoicesCreateAcceptedCoin,
    ),
  );
}

export function paymentInvoicesCreateAcceptedCoinFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesCreateAcceptedCoin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesCreateAcceptedCoin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesCreateAcceptedCoin' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesCreateResponse$inboundSchema: z.ZodType<
  PaymentInvoicesCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PaymentInvoicesCreateStatus$inboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  returnUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PaymentInvoicesCreatePayCurrency$inboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PaymentInvoicesCreateAcceptedCoin$inboundSchema),
  ),
  paymentUrl: z.string(),
});

/** @internal */
export type PaymentInvoicesCreateResponse$Outbound = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: string;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  returnUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PaymentInvoicesCreatePayCurrency$Outbound | null;
  acceptedCoins: Array<PaymentInvoicesCreateAcceptedCoin$Outbound>;
  paymentUrl: string;
};

/** @internal */
export const PaymentInvoicesCreateResponse$outboundSchema: z.ZodType<
  PaymentInvoicesCreateResponse$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesCreateResponse
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PaymentInvoicesCreateStatus$outboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  returnUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PaymentInvoicesCreatePayCurrency$outboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PaymentInvoicesCreateAcceptedCoin$outboundSchema),
  ),
  paymentUrl: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateResponse$ {
  /** @deprecated use `PaymentInvoicesCreateResponse$inboundSchema` instead. */
  export const inboundSchema = PaymentInvoicesCreateResponse$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateResponse$outboundSchema` instead. */
  export const outboundSchema = PaymentInvoicesCreateResponse$outboundSchema;
  /** @deprecated use `PaymentInvoicesCreateResponse$Outbound` instead. */
  export type Outbound = PaymentInvoicesCreateResponse$Outbound;
}

export function paymentInvoicesCreateResponseToJSON(
  paymentInvoicesCreateResponse: PaymentInvoicesCreateResponse,
): string {
  return JSON.stringify(
    PaymentInvoicesCreateResponse$outboundSchema.parse(
      paymentInvoicesCreateResponse,
    ),
  );
}

export function paymentInvoicesCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentInvoicesCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesCreateResponse' from JSON`,
  );
}
