/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PaymentInvoicesCreateWhiteLabelRequest = {
  feePaidByPayer?: boolean | undefined;
  callbackUrl?: string | null | undefined;
  amount: number;
  amountCurrency?: string | undefined;
  underPaidCover?: number | undefined;
  lifeTime?: number | undefined;
  payAddress: string | null;
  payinExtraId: string | null;
  payCurrency: string;
};

export const PaymentInvoicesCreateWhiteLabelStatus = {
  Waiting: "waiting",
  Confirming: "confirming",
  Confirmed: "confirmed",
  Sending: "sending",
  PartiallyPaid: "partially_paid",
  Finished: "finished",
  Failed: "failed",
  Expired: "expired",
} as const;
export type PaymentInvoicesCreateWhiteLabelStatus = ClosedEnum<
  typeof PaymentInvoicesCreateWhiteLabelStatus
>;

export type PaymentInvoicesCreateWhiteLabelPayCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PaymentInvoicesCreateWhiteLabelAcceptedCoin = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type PaymentInvoicesCreateWhiteLabelResponse = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: PaymentInvoicesCreateWhiteLabelStatus;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PaymentInvoicesCreateWhiteLabelPayCurrency | null;
  acceptedCoins: Array<PaymentInvoicesCreateWhiteLabelAcceptedCoin>;
};

/** @internal */
export const PaymentInvoicesCreateWhiteLabelRequest$inboundSchema: z.ZodType<
  PaymentInvoicesCreateWhiteLabelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  feePaidByPayer: z.boolean().optional(),
  callbackUrl: z.nullable(z.string()).optional(),
  amount: z.number(),
  amountCurrency: z.string().default("USD"),
  underPaidCover: z.number().optional(),
  lifeTime: z.number().default(10080),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payCurrency: z.string(),
});

/** @internal */
export type PaymentInvoicesCreateWhiteLabelRequest$Outbound = {
  feePaidByPayer?: boolean | undefined;
  callbackUrl?: string | null | undefined;
  amount: number;
  amountCurrency: string;
  underPaidCover?: number | undefined;
  lifeTime: number;
  payAddress: string | null;
  payinExtraId: string | null;
  payCurrency: string;
};

/** @internal */
export const PaymentInvoicesCreateWhiteLabelRequest$outboundSchema: z.ZodType<
  PaymentInvoicesCreateWhiteLabelRequest$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesCreateWhiteLabelRequest
> = z.object({
  feePaidByPayer: z.boolean().optional(),
  callbackUrl: z.nullable(z.string()).optional(),
  amount: z.number(),
  amountCurrency: z.string().default("USD"),
  underPaidCover: z.number().optional(),
  lifeTime: z.number().default(10080),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payCurrency: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateWhiteLabelRequest$ {
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelRequest$inboundSchema` instead. */
  export const inboundSchema =
    PaymentInvoicesCreateWhiteLabelRequest$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelRequest$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesCreateWhiteLabelRequest$outboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelRequest$Outbound` instead. */
  export type Outbound = PaymentInvoicesCreateWhiteLabelRequest$Outbound;
}

export function paymentInvoicesCreateWhiteLabelRequestToJSON(
  paymentInvoicesCreateWhiteLabelRequest:
    PaymentInvoicesCreateWhiteLabelRequest,
): string {
  return JSON.stringify(
    PaymentInvoicesCreateWhiteLabelRequest$outboundSchema.parse(
      paymentInvoicesCreateWhiteLabelRequest,
    ),
  );
}

export function paymentInvoicesCreateWhiteLabelRequestFromJSON(
  jsonString: string,
): SafeParseResult<PaymentInvoicesCreateWhiteLabelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaymentInvoicesCreateWhiteLabelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentInvoicesCreateWhiteLabelRequest' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesCreateWhiteLabelStatus$inboundSchema:
  z.ZodNativeEnum<typeof PaymentInvoicesCreateWhiteLabelStatus> = z.nativeEnum(
    PaymentInvoicesCreateWhiteLabelStatus,
  );

/** @internal */
export const PaymentInvoicesCreateWhiteLabelStatus$outboundSchema:
  z.ZodNativeEnum<typeof PaymentInvoicesCreateWhiteLabelStatus> =
    PaymentInvoicesCreateWhiteLabelStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateWhiteLabelStatus$ {
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelStatus$inboundSchema` instead. */
  export const inboundSchema =
    PaymentInvoicesCreateWhiteLabelStatus$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelStatus$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesCreateWhiteLabelStatus$outboundSchema;
}

/** @internal */
export const PaymentInvoicesCreateWhiteLabelPayCurrency$inboundSchema:
  z.ZodType<PaymentInvoicesCreateWhiteLabelPayCurrency, z.ZodTypeDef, unknown> =
    z.object({
      id: z.string(),
      code: z.string(),
      name: z.string(),
      enabled: z.boolean(),
      walletRegex: z.string(),
      priority: z.number().int(),
      extraIdExists: z.boolean(),
      extraIdRegex: z.nullable(z.string()),
      usdPrice: z.string(),
      minPaymentAmount: z.string(),
      minPayoutAmount: z.string(),
      minWithdrawalFeeEstimate: z.string(),
      logoUrl: z.nullable(z.string()),
      track: z.boolean(),
      cgId: z.nullable(z.string()),
      isMaxlimit: z.boolean(),
      network: z.nullable(z.string()),
      smartContract: z.nullable(z.string()),
      networkPrecision: z.nullable(z.string()),
      explorerLinkHash: z.nullable(z.string()),
      precision: z.number().int(),
      ticker: z.nullable(z.string()),
      isDefi: z.boolean(),
      isPopular: z.boolean(),
      isStable: z.boolean(),
      availableForToConversion: z.boolean(),
      createdAt: z.string(),
      updatedAt: z.string(),
    });

/** @internal */
export type PaymentInvoicesCreateWhiteLabelPayCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PaymentInvoicesCreateWhiteLabelPayCurrency$outboundSchema:
  z.ZodType<
    PaymentInvoicesCreateWhiteLabelPayCurrency$Outbound,
    z.ZodTypeDef,
    PaymentInvoicesCreateWhiteLabelPayCurrency
  > = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    enabled: z.boolean(),
    walletRegex: z.string(),
    priority: z.number().int(),
    extraIdExists: z.boolean(),
    extraIdRegex: z.nullable(z.string()),
    usdPrice: z.string(),
    minPaymentAmount: z.string(),
    minPayoutAmount: z.string(),
    minWithdrawalFeeEstimate: z.string(),
    logoUrl: z.nullable(z.string()),
    track: z.boolean(),
    cgId: z.nullable(z.string()),
    isMaxlimit: z.boolean(),
    network: z.nullable(z.string()),
    smartContract: z.nullable(z.string()),
    networkPrecision: z.nullable(z.string()),
    explorerLinkHash: z.nullable(z.string()),
    precision: z.number().int(),
    ticker: z.nullable(z.string()),
    isDefi: z.boolean(),
    isPopular: z.boolean(),
    isStable: z.boolean(),
    availableForToConversion: z.boolean(),
    createdAt: z.string(),
    updatedAt: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateWhiteLabelPayCurrency$ {
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelPayCurrency$inboundSchema` instead. */
  export const inboundSchema =
    PaymentInvoicesCreateWhiteLabelPayCurrency$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelPayCurrency$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesCreateWhiteLabelPayCurrency$outboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelPayCurrency$Outbound` instead. */
  export type Outbound = PaymentInvoicesCreateWhiteLabelPayCurrency$Outbound;
}

export function paymentInvoicesCreateWhiteLabelPayCurrencyToJSON(
  paymentInvoicesCreateWhiteLabelPayCurrency:
    PaymentInvoicesCreateWhiteLabelPayCurrency,
): string {
  return JSON.stringify(
    PaymentInvoicesCreateWhiteLabelPayCurrency$outboundSchema.parse(
      paymentInvoicesCreateWhiteLabelPayCurrency,
    ),
  );
}

export function paymentInvoicesCreateWhiteLabelPayCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<
  PaymentInvoicesCreateWhiteLabelPayCurrency,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaymentInvoicesCreateWhiteLabelPayCurrency$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaymentInvoicesCreateWhiteLabelPayCurrency' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesCreateWhiteLabelAcceptedCoin$inboundSchema:
  z.ZodType<
    PaymentInvoicesCreateWhiteLabelAcceptedCoin,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    enabled: z.boolean(),
    walletRegex: z.string(),
    priority: z.number().int(),
    extraIdExists: z.boolean(),
    extraIdRegex: z.nullable(z.string()),
    usdPrice: z.string(),
    minPaymentAmount: z.string(),
    minPayoutAmount: z.string(),
    minWithdrawalFeeEstimate: z.string(),
    logoUrl: z.nullable(z.string()),
    track: z.boolean(),
    cgId: z.nullable(z.string()),
    isMaxlimit: z.boolean(),
    network: z.nullable(z.string()),
    smartContract: z.nullable(z.string()),
    networkPrecision: z.nullable(z.string()),
    explorerLinkHash: z.nullable(z.string()),
    precision: z.number().int(),
    ticker: z.nullable(z.string()),
    isDefi: z.boolean(),
    isPopular: z.boolean(),
    isStable: z.boolean(),
    availableForToConversion: z.boolean(),
    createdAt: z.string(),
    updatedAt: z.string(),
  });

/** @internal */
export type PaymentInvoicesCreateWhiteLabelAcceptedCoin$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PaymentInvoicesCreateWhiteLabelAcceptedCoin$outboundSchema:
  z.ZodType<
    PaymentInvoicesCreateWhiteLabelAcceptedCoin$Outbound,
    z.ZodTypeDef,
    PaymentInvoicesCreateWhiteLabelAcceptedCoin
  > = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    enabled: z.boolean(),
    walletRegex: z.string(),
    priority: z.number().int(),
    extraIdExists: z.boolean(),
    extraIdRegex: z.nullable(z.string()),
    usdPrice: z.string(),
    minPaymentAmount: z.string(),
    minPayoutAmount: z.string(),
    minWithdrawalFeeEstimate: z.string(),
    logoUrl: z.nullable(z.string()),
    track: z.boolean(),
    cgId: z.nullable(z.string()),
    isMaxlimit: z.boolean(),
    network: z.nullable(z.string()),
    smartContract: z.nullable(z.string()),
    networkPrecision: z.nullable(z.string()),
    explorerLinkHash: z.nullable(z.string()),
    precision: z.number().int(),
    ticker: z.nullable(z.string()),
    isDefi: z.boolean(),
    isPopular: z.boolean(),
    isStable: z.boolean(),
    availableForToConversion: z.boolean(),
    createdAt: z.string(),
    updatedAt: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateWhiteLabelAcceptedCoin$ {
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelAcceptedCoin$inboundSchema` instead. */
  export const inboundSchema =
    PaymentInvoicesCreateWhiteLabelAcceptedCoin$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelAcceptedCoin$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesCreateWhiteLabelAcceptedCoin$outboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelAcceptedCoin$Outbound` instead. */
  export type Outbound = PaymentInvoicesCreateWhiteLabelAcceptedCoin$Outbound;
}

export function paymentInvoicesCreateWhiteLabelAcceptedCoinToJSON(
  paymentInvoicesCreateWhiteLabelAcceptedCoin:
    PaymentInvoicesCreateWhiteLabelAcceptedCoin,
): string {
  return JSON.stringify(
    PaymentInvoicesCreateWhiteLabelAcceptedCoin$outboundSchema.parse(
      paymentInvoicesCreateWhiteLabelAcceptedCoin,
    ),
  );
}

export function paymentInvoicesCreateWhiteLabelAcceptedCoinFromJSON(
  jsonString: string,
): SafeParseResult<
  PaymentInvoicesCreateWhiteLabelAcceptedCoin,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaymentInvoicesCreateWhiteLabelAcceptedCoin$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaymentInvoicesCreateWhiteLabelAcceptedCoin' from JSON`,
  );
}

/** @internal */
export const PaymentInvoicesCreateWhiteLabelResponse$inboundSchema: z.ZodType<
  PaymentInvoicesCreateWhiteLabelResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PaymentInvoicesCreateWhiteLabelStatus$inboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PaymentInvoicesCreateWhiteLabelPayCurrency$inboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PaymentInvoicesCreateWhiteLabelAcceptedCoin$inboundSchema),
  ),
});

/** @internal */
export type PaymentInvoicesCreateWhiteLabelResponse$Outbound = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: string;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PaymentInvoicesCreateWhiteLabelPayCurrency$Outbound | null;
  acceptedCoins: Array<PaymentInvoicesCreateWhiteLabelAcceptedCoin$Outbound>;
};

/** @internal */
export const PaymentInvoicesCreateWhiteLabelResponse$outboundSchema: z.ZodType<
  PaymentInvoicesCreateWhiteLabelResponse$Outbound,
  z.ZodTypeDef,
  PaymentInvoicesCreateWhiteLabelResponse
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PaymentInvoicesCreateWhiteLabelStatus$outboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PaymentInvoicesCreateWhiteLabelPayCurrency$outboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PaymentInvoicesCreateWhiteLabelAcceptedCoin$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentInvoicesCreateWhiteLabelResponse$ {
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelResponse$inboundSchema` instead. */
  export const inboundSchema =
    PaymentInvoicesCreateWhiteLabelResponse$inboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelResponse$outboundSchema` instead. */
  export const outboundSchema =
    PaymentInvoicesCreateWhiteLabelResponse$outboundSchema;
  /** @deprecated use `PaymentInvoicesCreateWhiteLabelResponse$Outbound` instead. */
  export type Outbound = PaymentInvoicesCreateWhiteLabelResponse$Outbound;
}

export function paymentInvoicesCreateWhiteLabelResponseToJSON(
  paymentInvoicesCreateWhiteLabelResponse:
    PaymentInvoicesCreateWhiteLabelResponse,
): string {
  return JSON.stringify(
    PaymentInvoicesCreateWhiteLabelResponse$outboundSchema.parse(
      paymentInvoicesCreateWhiteLabelResponse,
    ),
  );
}

export function paymentInvoicesCreateWhiteLabelResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PaymentInvoicesCreateWhiteLabelResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaymentInvoicesCreateWhiteLabelResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaymentInvoicesCreateWhiteLabelResponse' from JSON`,
  );
}
