/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PayoutsGetByIdRequest = {
  id: string;
};

export const PayoutsGetByIdStatus = {
  Waiting: "waiting",
  Confirming: "confirming",
  Confirmed: "confirmed",
  Sending: "sending",
  PartiallyPaid: "partially_paid",
  Finished: "finished",
  Failed: "failed",
  Expired: "expired",
} as const;
export type PayoutsGetByIdStatus = ClosedEnum<typeof PayoutsGetByIdStatus>;

export type PayoutsGetByIdPayCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PayoutsGetByIdAcceptedCoin = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type PayoutsGetByIdResponse = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: PayoutsGetByIdStatus;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  returnUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PayoutsGetByIdPayCurrency | null;
  acceptedCoins: Array<PayoutsGetByIdAcceptedCoin>;
};

/** @internal */
export const PayoutsGetByIdRequest$inboundSchema: z.ZodType<
  PayoutsGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type PayoutsGetByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const PayoutsGetByIdRequest$outboundSchema: z.ZodType<
  PayoutsGetByIdRequest$Outbound,
  z.ZodTypeDef,
  PayoutsGetByIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdRequest$ {
  /** @deprecated use `PayoutsGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdRequest$inboundSchema;
  /** @deprecated use `PayoutsGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdRequest$outboundSchema;
  /** @deprecated use `PayoutsGetByIdRequest$Outbound` instead. */
  export type Outbound = PayoutsGetByIdRequest$Outbound;
}

export function payoutsGetByIdRequestToJSON(
  payoutsGetByIdRequest: PayoutsGetByIdRequest,
): string {
  return JSON.stringify(
    PayoutsGetByIdRequest$outboundSchema.parse(payoutsGetByIdRequest),
  );
}

export function payoutsGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetByIdRequest' from JSON`,
  );
}

/** @internal */
export const PayoutsGetByIdStatus$inboundSchema: z.ZodNativeEnum<
  typeof PayoutsGetByIdStatus
> = z.nativeEnum(PayoutsGetByIdStatus);

/** @internal */
export const PayoutsGetByIdStatus$outboundSchema: z.ZodNativeEnum<
  typeof PayoutsGetByIdStatus
> = PayoutsGetByIdStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdStatus$ {
  /** @deprecated use `PayoutsGetByIdStatus$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdStatus$inboundSchema;
  /** @deprecated use `PayoutsGetByIdStatus$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdStatus$outboundSchema;
}

/** @internal */
export const PayoutsGetByIdPayCurrency$inboundSchema: z.ZodType<
  PayoutsGetByIdPayCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PayoutsGetByIdPayCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PayoutsGetByIdPayCurrency$outboundSchema: z.ZodType<
  PayoutsGetByIdPayCurrency$Outbound,
  z.ZodTypeDef,
  PayoutsGetByIdPayCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdPayCurrency$ {
  /** @deprecated use `PayoutsGetByIdPayCurrency$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdPayCurrency$inboundSchema;
  /** @deprecated use `PayoutsGetByIdPayCurrency$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdPayCurrency$outboundSchema;
  /** @deprecated use `PayoutsGetByIdPayCurrency$Outbound` instead. */
  export type Outbound = PayoutsGetByIdPayCurrency$Outbound;
}

export function payoutsGetByIdPayCurrencyToJSON(
  payoutsGetByIdPayCurrency: PayoutsGetByIdPayCurrency,
): string {
  return JSON.stringify(
    PayoutsGetByIdPayCurrency$outboundSchema.parse(payoutsGetByIdPayCurrency),
  );
}

export function payoutsGetByIdPayCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetByIdPayCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetByIdPayCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetByIdPayCurrency' from JSON`,
  );
}

/** @internal */
export const PayoutsGetByIdAcceptedCoin$inboundSchema: z.ZodType<
  PayoutsGetByIdAcceptedCoin,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PayoutsGetByIdAcceptedCoin$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PayoutsGetByIdAcceptedCoin$outboundSchema: z.ZodType<
  PayoutsGetByIdAcceptedCoin$Outbound,
  z.ZodTypeDef,
  PayoutsGetByIdAcceptedCoin
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdAcceptedCoin$ {
  /** @deprecated use `PayoutsGetByIdAcceptedCoin$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdAcceptedCoin$inboundSchema;
  /** @deprecated use `PayoutsGetByIdAcceptedCoin$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdAcceptedCoin$outboundSchema;
  /** @deprecated use `PayoutsGetByIdAcceptedCoin$Outbound` instead. */
  export type Outbound = PayoutsGetByIdAcceptedCoin$Outbound;
}

export function payoutsGetByIdAcceptedCoinToJSON(
  payoutsGetByIdAcceptedCoin: PayoutsGetByIdAcceptedCoin,
): string {
  return JSON.stringify(
    PayoutsGetByIdAcceptedCoin$outboundSchema.parse(payoutsGetByIdAcceptedCoin),
  );
}

export function payoutsGetByIdAcceptedCoinFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetByIdAcceptedCoin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetByIdAcceptedCoin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetByIdAcceptedCoin' from JSON`,
  );
}

/** @internal */
export const PayoutsGetByIdResponse$inboundSchema: z.ZodType<
  PayoutsGetByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PayoutsGetByIdStatus$inboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  returnUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PayoutsGetByIdPayCurrency$inboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PayoutsGetByIdAcceptedCoin$inboundSchema),
  ),
});

/** @internal */
export type PayoutsGetByIdResponse$Outbound = {
  id: string;
  walletId: string | null;
  merchantId: string;
  status: string;
  underPaidCover: string;
  feePaidByPayer: boolean;
  isWhiteLabel: boolean;
  priceAmount: string;
  priceCurrency: string;
  payAmount: string | null;
  paidAmount: string;
  receivedAmount: string;
  payAddress: string | null;
  payinExtraId: string | null;
  payinHash: string | null;
  orderId: string | null;
  orderDescription: string | null;
  callbackUrl: string | null;
  returnUrl: string | null;
  finishedAt: string | null;
  expiredAt: string;
  createdAt: string;
  updatedAt: string;
  payCurrency: PayoutsGetByIdPayCurrency$Outbound | null;
  acceptedCoins: Array<PayoutsGetByIdAcceptedCoin$Outbound>;
};

/** @internal */
export const PayoutsGetByIdResponse$outboundSchema: z.ZodType<
  PayoutsGetByIdResponse$Outbound,
  z.ZodTypeDef,
  PayoutsGetByIdResponse
> = z.object({
  id: z.string(),
  walletId: z.nullable(z.string()),
  merchantId: z.string(),
  status: PayoutsGetByIdStatus$outboundSchema,
  underPaidCover: z.string(),
  feePaidByPayer: z.boolean(),
  isWhiteLabel: z.boolean(),
  priceAmount: z.string(),
  priceCurrency: z.string(),
  payAmount: z.nullable(z.string()),
  paidAmount: z.string(),
  receivedAmount: z.string(),
  payAddress: z.nullable(z.string()),
  payinExtraId: z.nullable(z.string()),
  payinHash: z.nullable(z.string()),
  orderId: z.nullable(z.string()),
  orderDescription: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  returnUrl: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  expiredAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  payCurrency: z.nullable(
    z.lazy(() => PayoutsGetByIdPayCurrency$outboundSchema),
  ),
  acceptedCoins: z.array(
    z.lazy(() => PayoutsGetByIdAcceptedCoin$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdResponse$ {
  /** @deprecated use `PayoutsGetByIdResponse$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdResponse$inboundSchema;
  /** @deprecated use `PayoutsGetByIdResponse$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdResponse$outboundSchema;
  /** @deprecated use `PayoutsGetByIdResponse$Outbound` instead. */
  export type Outbound = PayoutsGetByIdResponse$Outbound;
}

export function payoutsGetByIdResponseToJSON(
  payoutsGetByIdResponse: PayoutsGetByIdResponse,
): string {
  return JSON.stringify(
    PayoutsGetByIdResponse$outboundSchema.parse(payoutsGetByIdResponse),
  );
}

export function payoutsGetByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetByIdResponse' from JSON`,
  );
}
