/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Successful response
 */
export type PayoutsGetStatsResponse = {
  total: number;
  totalUSDAmount: number;
  totalReceipients: number;
  totalProcessing: number;
  totalFinished: number;
};

/** @internal */
export const PayoutsGetStatsResponse$inboundSchema: z.ZodType<
  PayoutsGetStatsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number(),
  totalUSDAmount: z.number(),
  totalReceipients: z.number(),
  totalProcessing: z.number(),
  totalFinished: z.number(),
});

/** @internal */
export type PayoutsGetStatsResponse$Outbound = {
  total: number;
  totalUSDAmount: number;
  totalReceipients: number;
  totalProcessing: number;
  totalFinished: number;
};

/** @internal */
export const PayoutsGetStatsResponse$outboundSchema: z.ZodType<
  PayoutsGetStatsResponse$Outbound,
  z.ZodTypeDef,
  PayoutsGetStatsResponse
> = z.object({
  total: z.number(),
  totalUSDAmount: z.number(),
  totalReceipients: z.number(),
  totalProcessing: z.number(),
  totalFinished: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetStatsResponse$ {
  /** @deprecated use `PayoutsGetStatsResponse$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetStatsResponse$inboundSchema;
  /** @deprecated use `PayoutsGetStatsResponse$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetStatsResponse$outboundSchema;
  /** @deprecated use `PayoutsGetStatsResponse$Outbound` instead. */
  export type Outbound = PayoutsGetStatsResponse$Outbound;
}

export function payoutsGetStatsResponseToJSON(
  payoutsGetStatsResponse: PayoutsGetStatsResponse,
): string {
  return JSON.stringify(
    PayoutsGetStatsResponse$outboundSchema.parse(payoutsGetStatsResponse),
  );
}

export function payoutsGetStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetStatsResponse' from JSON`,
  );
}
