/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PayoutsGetFeeEstimateRequest = {
  currency: string;
  amount: string;
};

/**
 * Successful response
 */
export type PayoutsGetFeeEstimateResponse = {
  fee: number;
};

/** @internal */
export const PayoutsGetFeeEstimateRequest$inboundSchema: z.ZodType<
  PayoutsGetFeeEstimateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  currency: z.string(),
  amount: z.string(),
});

/** @internal */
export type PayoutsGetFeeEstimateRequest$Outbound = {
  currency: string;
  amount: string;
};

/** @internal */
export const PayoutsGetFeeEstimateRequest$outboundSchema: z.ZodType<
  PayoutsGetFeeEstimateRequest$Outbound,
  z.ZodTypeDef,
  PayoutsGetFeeEstimateRequest
> = z.object({
  currency: z.string(),
  amount: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetFeeEstimateRequest$ {
  /** @deprecated use `PayoutsGetFeeEstimateRequest$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetFeeEstimateRequest$inboundSchema;
  /** @deprecated use `PayoutsGetFeeEstimateRequest$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetFeeEstimateRequest$outboundSchema;
  /** @deprecated use `PayoutsGetFeeEstimateRequest$Outbound` instead. */
  export type Outbound = PayoutsGetFeeEstimateRequest$Outbound;
}

export function payoutsGetFeeEstimateRequestToJSON(
  payoutsGetFeeEstimateRequest: PayoutsGetFeeEstimateRequest,
): string {
  return JSON.stringify(
    PayoutsGetFeeEstimateRequest$outboundSchema.parse(
      payoutsGetFeeEstimateRequest,
    ),
  );
}

export function payoutsGetFeeEstimateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetFeeEstimateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetFeeEstimateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetFeeEstimateRequest' from JSON`,
  );
}

/** @internal */
export const PayoutsGetFeeEstimateResponse$inboundSchema: z.ZodType<
  PayoutsGetFeeEstimateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  fee: z.number(),
});

/** @internal */
export type PayoutsGetFeeEstimateResponse$Outbound = {
  fee: number;
};

/** @internal */
export const PayoutsGetFeeEstimateResponse$outboundSchema: z.ZodType<
  PayoutsGetFeeEstimateResponse$Outbound,
  z.ZodTypeDef,
  PayoutsGetFeeEstimateResponse
> = z.object({
  fee: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetFeeEstimateResponse$ {
  /** @deprecated use `PayoutsGetFeeEstimateResponse$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetFeeEstimateResponse$inboundSchema;
  /** @deprecated use `PayoutsGetFeeEstimateResponse$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetFeeEstimateResponse$outboundSchema;
  /** @deprecated use `PayoutsGetFeeEstimateResponse$Outbound` instead. */
  export type Outbound = PayoutsGetFeeEstimateResponse$Outbound;
}

export function payoutsGetFeeEstimateResponseToJSON(
  payoutsGetFeeEstimateResponse: PayoutsGetFeeEstimateResponse,
): string {
  return JSON.stringify(
    PayoutsGetFeeEstimateResponse$outboundSchema.parse(
      payoutsGetFeeEstimateResponse,
    ),
  );
}

export function payoutsGetFeeEstimateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetFeeEstimateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetFeeEstimateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetFeeEstimateResponse' from JSON`,
  );
}
