/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PayoutsGetMinAmountRequest = {
  currency: string;
};

/**
 * Successful response
 */
export type PayoutsGetMinAmountResponse = {
  minAmount: number;
};

/** @internal */
export const PayoutsGetMinAmountRequest$inboundSchema: z.ZodType<
  PayoutsGetMinAmountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  currency: z.string(),
});

/** @internal */
export type PayoutsGetMinAmountRequest$Outbound = {
  currency: string;
};

/** @internal */
export const PayoutsGetMinAmountRequest$outboundSchema: z.ZodType<
  PayoutsGetMinAmountRequest$Outbound,
  z.ZodTypeDef,
  PayoutsGetMinAmountRequest
> = z.object({
  currency: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetMinAmountRequest$ {
  /** @deprecated use `PayoutsGetMinAmountRequest$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetMinAmountRequest$inboundSchema;
  /** @deprecated use `PayoutsGetMinAmountRequest$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetMinAmountRequest$outboundSchema;
  /** @deprecated use `PayoutsGetMinAmountRequest$Outbound` instead. */
  export type Outbound = PayoutsGetMinAmountRequest$Outbound;
}

export function payoutsGetMinAmountRequestToJSON(
  payoutsGetMinAmountRequest: PayoutsGetMinAmountRequest,
): string {
  return JSON.stringify(
    PayoutsGetMinAmountRequest$outboundSchema.parse(payoutsGetMinAmountRequest),
  );
}

export function payoutsGetMinAmountRequestFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetMinAmountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetMinAmountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetMinAmountRequest' from JSON`,
  );
}

/** @internal */
export const PayoutsGetMinAmountResponse$inboundSchema: z.ZodType<
  PayoutsGetMinAmountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  minAmount: z.number(),
});

/** @internal */
export type PayoutsGetMinAmountResponse$Outbound = {
  minAmount: number;
};

/** @internal */
export const PayoutsGetMinAmountResponse$outboundSchema: z.ZodType<
  PayoutsGetMinAmountResponse$Outbound,
  z.ZodTypeDef,
  PayoutsGetMinAmountResponse
> = z.object({
  minAmount: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetMinAmountResponse$ {
  /** @deprecated use `PayoutsGetMinAmountResponse$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetMinAmountResponse$inboundSchema;
  /** @deprecated use `PayoutsGetMinAmountResponse$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetMinAmountResponse$outboundSchema;
  /** @deprecated use `PayoutsGetMinAmountResponse$Outbound` instead. */
  export type Outbound = PayoutsGetMinAmountResponse$Outbound;
}

export function payoutsGetMinAmountResponseToJSON(
  payoutsGetMinAmountResponse: PayoutsGetMinAmountResponse,
): string {
  return JSON.stringify(
    PayoutsGetMinAmountResponse$outboundSchema.parse(
      payoutsGetMinAmountResponse,
    ),
  );
}

export function payoutsGetMinAmountResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetMinAmountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetMinAmountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetMinAmountResponse' from JSON`,
  );
}
