/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PayoutsListOwnedFilter = {
  createdStart?: string | null | undefined;
  createdEnd?: string | null | undefined;
  merchants?: Array<string> | null | undefined;
  q?: string | null | undefined;
};

export type PayoutsListOwnedRequest = {
  filter?: PayoutsListOwnedFilter | undefined;
  sort?: Array<string> | null | undefined;
  cursor?: string | undefined;
  pageSize?: number | undefined;
};

export type PayoutsListOwnedCursor = string | any;

export type PayoutsListOwnedMeta = {
  cursor?: string | any | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

export const PayoutsListOwnedStatus = {
  Creating: "creating",
  Waiting: "waiting",
  Processing: "processing",
  Sending: "sending",
  Finished: "finished",
  Failed: "failed",
  Rejected: "rejected",
} as const;
export type PayoutsListOwnedStatus = ClosedEnum<typeof PayoutsListOwnedStatus>;

export type PayoutsListOwnedCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PayoutsListOwnedData = {
  id: string;
  walletId: string;
  merchantId: string;
  currencyId: string;
  status: PayoutsListOwnedStatus;
  amount: string;
  address: string;
  extraId: string | null;
  txHash: string | null;
  fee: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currency: PayoutsListOwnedCurrency | null;
};

/**
 * Successful response
 */
export type PayoutsListOwnedResponse = {
  meta: PayoutsListOwnedMeta;
  data: Array<PayoutsListOwnedData>;
};

/** @internal */
export const PayoutsListOwnedFilter$inboundSchema: z.ZodType<
  PayoutsListOwnedFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_start: z.nullable(z.string()).optional(),
  created_end: z.nullable(z.string()).optional(),
  merchants: z.nullable(z.array(z.string())).optional(),
  q: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_start": "createdStart",
    "created_end": "createdEnd",
  });
});

/** @internal */
export type PayoutsListOwnedFilter$Outbound = {
  created_start?: string | null | undefined;
  created_end?: string | null | undefined;
  merchants?: Array<string> | null | undefined;
  q?: string | null | undefined;
};

/** @internal */
export const PayoutsListOwnedFilter$outboundSchema: z.ZodType<
  PayoutsListOwnedFilter$Outbound,
  z.ZodTypeDef,
  PayoutsListOwnedFilter
> = z.object({
  createdStart: z.nullable(z.string()).optional(),
  createdEnd: z.nullable(z.string()).optional(),
  merchants: z.nullable(z.array(z.string())).optional(),
  q: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    createdStart: "created_start",
    createdEnd: "created_end",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsListOwnedFilter$ {
  /** @deprecated use `PayoutsListOwnedFilter$inboundSchema` instead. */
  export const inboundSchema = PayoutsListOwnedFilter$inboundSchema;
  /** @deprecated use `PayoutsListOwnedFilter$outboundSchema` instead. */
  export const outboundSchema = PayoutsListOwnedFilter$outboundSchema;
  /** @deprecated use `PayoutsListOwnedFilter$Outbound` instead. */
  export type Outbound = PayoutsListOwnedFilter$Outbound;
}

export function payoutsListOwnedFilterToJSON(
  payoutsListOwnedFilter: PayoutsListOwnedFilter,
): string {
  return JSON.stringify(
    PayoutsListOwnedFilter$outboundSchema.parse(payoutsListOwnedFilter),
  );
}

export function payoutsListOwnedFilterFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsListOwnedFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsListOwnedFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsListOwnedFilter' from JSON`,
  );
}

/** @internal */
export const PayoutsListOwnedRequest$inboundSchema: z.ZodType<
  PayoutsListOwnedRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filter: z.lazy(() => PayoutsListOwnedFilter$inboundSchema).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  cursor: z.string().optional(),
  pageSize: z.number().optional(),
});

/** @internal */
export type PayoutsListOwnedRequest$Outbound = {
  filter?: PayoutsListOwnedFilter$Outbound | undefined;
  sort?: Array<string> | null | undefined;
  cursor?: string | undefined;
  pageSize?: number | undefined;
};

/** @internal */
export const PayoutsListOwnedRequest$outboundSchema: z.ZodType<
  PayoutsListOwnedRequest$Outbound,
  z.ZodTypeDef,
  PayoutsListOwnedRequest
> = z.object({
  filter: z.lazy(() => PayoutsListOwnedFilter$outboundSchema).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  cursor: z.string().optional(),
  pageSize: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsListOwnedRequest$ {
  /** @deprecated use `PayoutsListOwnedRequest$inboundSchema` instead. */
  export const inboundSchema = PayoutsListOwnedRequest$inboundSchema;
  /** @deprecated use `PayoutsListOwnedRequest$outboundSchema` instead. */
  export const outboundSchema = PayoutsListOwnedRequest$outboundSchema;
  /** @deprecated use `PayoutsListOwnedRequest$Outbound` instead. */
  export type Outbound = PayoutsListOwnedRequest$Outbound;
}

export function payoutsListOwnedRequestToJSON(
  payoutsListOwnedRequest: PayoutsListOwnedRequest,
): string {
  return JSON.stringify(
    PayoutsListOwnedRequest$outboundSchema.parse(payoutsListOwnedRequest),
  );
}

export function payoutsListOwnedRequestFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsListOwnedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsListOwnedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsListOwnedRequest' from JSON`,
  );
}

/** @internal */
export const PayoutsListOwnedCursor$inboundSchema: z.ZodType<
  PayoutsListOwnedCursor,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.any()]);

/** @internal */
export type PayoutsListOwnedCursor$Outbound = string | any;

/** @internal */
export const PayoutsListOwnedCursor$outboundSchema: z.ZodType<
  PayoutsListOwnedCursor$Outbound,
  z.ZodTypeDef,
  PayoutsListOwnedCursor
> = z.union([z.string(), z.any()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsListOwnedCursor$ {
  /** @deprecated use `PayoutsListOwnedCursor$inboundSchema` instead. */
  export const inboundSchema = PayoutsListOwnedCursor$inboundSchema;
  /** @deprecated use `PayoutsListOwnedCursor$outboundSchema` instead. */
  export const outboundSchema = PayoutsListOwnedCursor$outboundSchema;
  /** @deprecated use `PayoutsListOwnedCursor$Outbound` instead. */
  export type Outbound = PayoutsListOwnedCursor$Outbound;
}

export function payoutsListOwnedCursorToJSON(
  payoutsListOwnedCursor: PayoutsListOwnedCursor,
): string {
  return JSON.stringify(
    PayoutsListOwnedCursor$outboundSchema.parse(payoutsListOwnedCursor),
  );
}

export function payoutsListOwnedCursorFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsListOwnedCursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsListOwnedCursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsListOwnedCursor' from JSON`,
  );
}

/** @internal */
export const PayoutsListOwnedMeta$inboundSchema: z.ZodType<
  PayoutsListOwnedMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.union([z.string(), z.any()]).optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/** @internal */
export type PayoutsListOwnedMeta$Outbound = {
  cursor?: string | any | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/** @internal */
export const PayoutsListOwnedMeta$outboundSchema: z.ZodType<
  PayoutsListOwnedMeta$Outbound,
  z.ZodTypeDef,
  PayoutsListOwnedMeta
> = z.object({
  cursor: z.union([z.string(), z.any()]).optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsListOwnedMeta$ {
  /** @deprecated use `PayoutsListOwnedMeta$inboundSchema` instead. */
  export const inboundSchema = PayoutsListOwnedMeta$inboundSchema;
  /** @deprecated use `PayoutsListOwnedMeta$outboundSchema` instead. */
  export const outboundSchema = PayoutsListOwnedMeta$outboundSchema;
  /** @deprecated use `PayoutsListOwnedMeta$Outbound` instead. */
  export type Outbound = PayoutsListOwnedMeta$Outbound;
}

export function payoutsListOwnedMetaToJSON(
  payoutsListOwnedMeta: PayoutsListOwnedMeta,
): string {
  return JSON.stringify(
    PayoutsListOwnedMeta$outboundSchema.parse(payoutsListOwnedMeta),
  );
}

export function payoutsListOwnedMetaFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsListOwnedMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsListOwnedMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsListOwnedMeta' from JSON`,
  );
}

/** @internal */
export const PayoutsListOwnedStatus$inboundSchema: z.ZodNativeEnum<
  typeof PayoutsListOwnedStatus
> = z.nativeEnum(PayoutsListOwnedStatus);

/** @internal */
export const PayoutsListOwnedStatus$outboundSchema: z.ZodNativeEnum<
  typeof PayoutsListOwnedStatus
> = PayoutsListOwnedStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsListOwnedStatus$ {
  /** @deprecated use `PayoutsListOwnedStatus$inboundSchema` instead. */
  export const inboundSchema = PayoutsListOwnedStatus$inboundSchema;
  /** @deprecated use `PayoutsListOwnedStatus$outboundSchema` instead. */
  export const outboundSchema = PayoutsListOwnedStatus$outboundSchema;
}

/** @internal */
export const PayoutsListOwnedCurrency$inboundSchema: z.ZodType<
  PayoutsListOwnedCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PayoutsListOwnedCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PayoutsListOwnedCurrency$outboundSchema: z.ZodType<
  PayoutsListOwnedCurrency$Outbound,
  z.ZodTypeDef,
  PayoutsListOwnedCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsListOwnedCurrency$ {
  /** @deprecated use `PayoutsListOwnedCurrency$inboundSchema` instead. */
  export const inboundSchema = PayoutsListOwnedCurrency$inboundSchema;
  /** @deprecated use `PayoutsListOwnedCurrency$outboundSchema` instead. */
  export const outboundSchema = PayoutsListOwnedCurrency$outboundSchema;
  /** @deprecated use `PayoutsListOwnedCurrency$Outbound` instead. */
  export type Outbound = PayoutsListOwnedCurrency$Outbound;
}

export function payoutsListOwnedCurrencyToJSON(
  payoutsListOwnedCurrency: PayoutsListOwnedCurrency,
): string {
  return JSON.stringify(
    PayoutsListOwnedCurrency$outboundSchema.parse(payoutsListOwnedCurrency),
  );
}

export function payoutsListOwnedCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsListOwnedCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsListOwnedCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsListOwnedCurrency' from JSON`,
  );
}

/** @internal */
export const PayoutsListOwnedData$inboundSchema: z.ZodType<
  PayoutsListOwnedData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  walletId: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  status: PayoutsListOwnedStatus$inboundSchema,
  amount: z.string(),
  address: z.string(),
  extraId: z.nullable(z.string()),
  txHash: z.nullable(z.string()),
  fee: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.nullable(z.lazy(() => PayoutsListOwnedCurrency$inboundSchema)),
});

/** @internal */
export type PayoutsListOwnedData$Outbound = {
  id: string;
  walletId: string;
  merchantId: string;
  currencyId: string;
  status: string;
  amount: string;
  address: string;
  extraId: string | null;
  txHash: string | null;
  fee: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currency: PayoutsListOwnedCurrency$Outbound | null;
};

/** @internal */
export const PayoutsListOwnedData$outboundSchema: z.ZodType<
  PayoutsListOwnedData$Outbound,
  z.ZodTypeDef,
  PayoutsListOwnedData
> = z.object({
  id: z.string(),
  walletId: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  status: PayoutsListOwnedStatus$outboundSchema,
  amount: z.string(),
  address: z.string(),
  extraId: z.nullable(z.string()),
  txHash: z.nullable(z.string()),
  fee: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.nullable(z.lazy(() => PayoutsListOwnedCurrency$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsListOwnedData$ {
  /** @deprecated use `PayoutsListOwnedData$inboundSchema` instead. */
  export const inboundSchema = PayoutsListOwnedData$inboundSchema;
  /** @deprecated use `PayoutsListOwnedData$outboundSchema` instead. */
  export const outboundSchema = PayoutsListOwnedData$outboundSchema;
  /** @deprecated use `PayoutsListOwnedData$Outbound` instead. */
  export type Outbound = PayoutsListOwnedData$Outbound;
}

export function payoutsListOwnedDataToJSON(
  payoutsListOwnedData: PayoutsListOwnedData,
): string {
  return JSON.stringify(
    PayoutsListOwnedData$outboundSchema.parse(payoutsListOwnedData),
  );
}

export function payoutsListOwnedDataFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsListOwnedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsListOwnedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsListOwnedData' from JSON`,
  );
}

/** @internal */
export const PayoutsListOwnedResponse$inboundSchema: z.ZodType<
  PayoutsListOwnedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: z.lazy(() => PayoutsListOwnedMeta$inboundSchema),
  data: z.array(z.lazy(() => PayoutsListOwnedData$inboundSchema)),
});

/** @internal */
export type PayoutsListOwnedResponse$Outbound = {
  meta: PayoutsListOwnedMeta$Outbound;
  data: Array<PayoutsListOwnedData$Outbound>;
};

/** @internal */
export const PayoutsListOwnedResponse$outboundSchema: z.ZodType<
  PayoutsListOwnedResponse$Outbound,
  z.ZodTypeDef,
  PayoutsListOwnedResponse
> = z.object({
  meta: z.lazy(() => PayoutsListOwnedMeta$outboundSchema),
  data: z.array(z.lazy(() => PayoutsListOwnedData$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsListOwnedResponse$ {
  /** @deprecated use `PayoutsListOwnedResponse$inboundSchema` instead. */
  export const inboundSchema = PayoutsListOwnedResponse$inboundSchema;
  /** @deprecated use `PayoutsListOwnedResponse$outboundSchema` instead. */
  export const outboundSchema = PayoutsListOwnedResponse$outboundSchema;
  /** @deprecated use `PayoutsListOwnedResponse$Outbound` instead. */
  export type Outbound = PayoutsListOwnedResponse$Outbound;
}

export function payoutsListOwnedResponseToJSON(
  payoutsListOwnedResponse: PayoutsListOwnedResponse,
): string {
  return JSON.stringify(
    PayoutsListOwnedResponse$outboundSchema.parse(payoutsListOwnedResponse),
  );
}

export function payoutsListOwnedResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsListOwnedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsListOwnedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsListOwnedResponse' from JSON`,
  );
}
