/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PayoutsCreateRequest = {
  amount: string;
  address: string;
  extraId?: string | null | undefined;
  callbackUrl?: string | null | undefined;
  currency: string;
};

export const PayoutsCreateStatus = {
  Creating: "creating",
  Waiting: "waiting",
  Processing: "processing",
  Sending: "sending",
  Finished: "finished",
  Failed: "failed",
  Rejected: "rejected",
} as const;
export type PayoutsCreateStatus = ClosedEnum<typeof PayoutsCreateStatus>;

export type PayoutsCreateCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type PayoutsCreateResponse = {
  id: string;
  walletId: string;
  merchantId: string;
  currencyId: string;
  status: PayoutsCreateStatus;
  amount: string;
  address: string;
  extraId: string | null;
  txHash: string | null;
  fee: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currency: PayoutsCreateCurrency | null;
};

/** @internal */
export const PayoutsCreateRequest$inboundSchema: z.ZodType<
  PayoutsCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.string(),
  address: z.string(),
  extraId: z.nullable(z.string()).optional(),
  callbackUrl: z.nullable(z.string()).optional(),
  currency: z.string(),
});

/** @internal */
export type PayoutsCreateRequest$Outbound = {
  amount: string;
  address: string;
  extraId?: string | null | undefined;
  callbackUrl?: string | null | undefined;
  currency: string;
};

/** @internal */
export const PayoutsCreateRequest$outboundSchema: z.ZodType<
  PayoutsCreateRequest$Outbound,
  z.ZodTypeDef,
  PayoutsCreateRequest
> = z.object({
  amount: z.string(),
  address: z.string(),
  extraId: z.nullable(z.string()).optional(),
  callbackUrl: z.nullable(z.string()).optional(),
  currency: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsCreateRequest$ {
  /** @deprecated use `PayoutsCreateRequest$inboundSchema` instead. */
  export const inboundSchema = PayoutsCreateRequest$inboundSchema;
  /** @deprecated use `PayoutsCreateRequest$outboundSchema` instead. */
  export const outboundSchema = PayoutsCreateRequest$outboundSchema;
  /** @deprecated use `PayoutsCreateRequest$Outbound` instead. */
  export type Outbound = PayoutsCreateRequest$Outbound;
}

export function payoutsCreateRequestToJSON(
  payoutsCreateRequest: PayoutsCreateRequest,
): string {
  return JSON.stringify(
    PayoutsCreateRequest$outboundSchema.parse(payoutsCreateRequest),
  );
}

export function payoutsCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsCreateRequest' from JSON`,
  );
}

/** @internal */
export const PayoutsCreateStatus$inboundSchema: z.ZodNativeEnum<
  typeof PayoutsCreateStatus
> = z.nativeEnum(PayoutsCreateStatus);

/** @internal */
export const PayoutsCreateStatus$outboundSchema: z.ZodNativeEnum<
  typeof PayoutsCreateStatus
> = PayoutsCreateStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsCreateStatus$ {
  /** @deprecated use `PayoutsCreateStatus$inboundSchema` instead. */
  export const inboundSchema = PayoutsCreateStatus$inboundSchema;
  /** @deprecated use `PayoutsCreateStatus$outboundSchema` instead. */
  export const outboundSchema = PayoutsCreateStatus$outboundSchema;
}

/** @internal */
export const PayoutsCreateCurrency$inboundSchema: z.ZodType<
  PayoutsCreateCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PayoutsCreateCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PayoutsCreateCurrency$outboundSchema: z.ZodType<
  PayoutsCreateCurrency$Outbound,
  z.ZodTypeDef,
  PayoutsCreateCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsCreateCurrency$ {
  /** @deprecated use `PayoutsCreateCurrency$inboundSchema` instead. */
  export const inboundSchema = PayoutsCreateCurrency$inboundSchema;
  /** @deprecated use `PayoutsCreateCurrency$outboundSchema` instead. */
  export const outboundSchema = PayoutsCreateCurrency$outboundSchema;
  /** @deprecated use `PayoutsCreateCurrency$Outbound` instead. */
  export type Outbound = PayoutsCreateCurrency$Outbound;
}

export function payoutsCreateCurrencyToJSON(
  payoutsCreateCurrency: PayoutsCreateCurrency,
): string {
  return JSON.stringify(
    PayoutsCreateCurrency$outboundSchema.parse(payoutsCreateCurrency),
  );
}

export function payoutsCreateCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsCreateCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsCreateCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsCreateCurrency' from JSON`,
  );
}

/** @internal */
export const PayoutsCreateResponse$inboundSchema: z.ZodType<
  PayoutsCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  walletId: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  status: PayoutsCreateStatus$inboundSchema,
  amount: z.string(),
  address: z.string(),
  extraId: z.nullable(z.string()),
  txHash: z.nullable(z.string()),
  fee: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.nullable(z.lazy(() => PayoutsCreateCurrency$inboundSchema)),
});

/** @internal */
export type PayoutsCreateResponse$Outbound = {
  id: string;
  walletId: string;
  merchantId: string;
  currencyId: string;
  status: string;
  amount: string;
  address: string;
  extraId: string | null;
  txHash: string | null;
  fee: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currency: PayoutsCreateCurrency$Outbound | null;
};

/** @internal */
export const PayoutsCreateResponse$outboundSchema: z.ZodType<
  PayoutsCreateResponse$Outbound,
  z.ZodTypeDef,
  PayoutsCreateResponse
> = z.object({
  id: z.string(),
  walletId: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  status: PayoutsCreateStatus$outboundSchema,
  amount: z.string(),
  address: z.string(),
  extraId: z.nullable(z.string()),
  txHash: z.nullable(z.string()),
  fee: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.nullable(z.lazy(() => PayoutsCreateCurrency$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsCreateResponse$ {
  /** @deprecated use `PayoutsCreateResponse$inboundSchema` instead. */
  export const inboundSchema = PayoutsCreateResponse$inboundSchema;
  /** @deprecated use `PayoutsCreateResponse$outboundSchema` instead. */
  export const outboundSchema = PayoutsCreateResponse$outboundSchema;
  /** @deprecated use `PayoutsCreateResponse$Outbound` instead. */
  export type Outbound = PayoutsCreateResponse$Outbound;
}

export function payoutsCreateResponseToJSON(
  payoutsCreateResponse: PayoutsCreateResponse,
): string {
  return JSON.stringify(
    PayoutsCreateResponse$outboundSchema.parse(payoutsCreateResponse),
  );
}

export function payoutsCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsCreateResponse' from JSON`,
  );
}
