/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PayoutsGetByIdRequest = {
  id: string;
};

export const PayoutsGetByIdStatus = {
  Creating: "creating",
  Waiting: "waiting",
  Processing: "processing",
  Sending: "sending",
  Finished: "finished",
  Failed: "failed",
  Rejected: "rejected",
} as const;
export type PayoutsGetByIdStatus = ClosedEnum<typeof PayoutsGetByIdStatus>;

export type PayoutsGetByIdCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type PayoutsGetByIdResponse = {
  id: string;
  walletId: string;
  merchantId: string;
  currencyId: string;
  status: PayoutsGetByIdStatus;
  amount: string;
  address: string;
  extraId: string | null;
  txHash: string | null;
  fee: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currency: PayoutsGetByIdCurrency | null;
};

/** @internal */
export const PayoutsGetByIdRequest$inboundSchema: z.ZodType<
  PayoutsGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type PayoutsGetByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const PayoutsGetByIdRequest$outboundSchema: z.ZodType<
  PayoutsGetByIdRequest$Outbound,
  z.ZodTypeDef,
  PayoutsGetByIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdRequest$ {
  /** @deprecated use `PayoutsGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdRequest$inboundSchema;
  /** @deprecated use `PayoutsGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdRequest$outboundSchema;
  /** @deprecated use `PayoutsGetByIdRequest$Outbound` instead. */
  export type Outbound = PayoutsGetByIdRequest$Outbound;
}

export function payoutsGetByIdRequestToJSON(
  payoutsGetByIdRequest: PayoutsGetByIdRequest,
): string {
  return JSON.stringify(
    PayoutsGetByIdRequest$outboundSchema.parse(payoutsGetByIdRequest),
  );
}

export function payoutsGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetByIdRequest' from JSON`,
  );
}

/** @internal */
export const PayoutsGetByIdStatus$inboundSchema: z.ZodNativeEnum<
  typeof PayoutsGetByIdStatus
> = z.nativeEnum(PayoutsGetByIdStatus);

/** @internal */
export const PayoutsGetByIdStatus$outboundSchema: z.ZodNativeEnum<
  typeof PayoutsGetByIdStatus
> = PayoutsGetByIdStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdStatus$ {
  /** @deprecated use `PayoutsGetByIdStatus$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdStatus$inboundSchema;
  /** @deprecated use `PayoutsGetByIdStatus$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdStatus$outboundSchema;
}

/** @internal */
export const PayoutsGetByIdCurrency$inboundSchema: z.ZodType<
  PayoutsGetByIdCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type PayoutsGetByIdCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const PayoutsGetByIdCurrency$outboundSchema: z.ZodType<
  PayoutsGetByIdCurrency$Outbound,
  z.ZodTypeDef,
  PayoutsGetByIdCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdCurrency$ {
  /** @deprecated use `PayoutsGetByIdCurrency$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdCurrency$inboundSchema;
  /** @deprecated use `PayoutsGetByIdCurrency$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdCurrency$outboundSchema;
  /** @deprecated use `PayoutsGetByIdCurrency$Outbound` instead. */
  export type Outbound = PayoutsGetByIdCurrency$Outbound;
}

export function payoutsGetByIdCurrencyToJSON(
  payoutsGetByIdCurrency: PayoutsGetByIdCurrency,
): string {
  return JSON.stringify(
    PayoutsGetByIdCurrency$outboundSchema.parse(payoutsGetByIdCurrency),
  );
}

export function payoutsGetByIdCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetByIdCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetByIdCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetByIdCurrency' from JSON`,
  );
}

/** @internal */
export const PayoutsGetByIdResponse$inboundSchema: z.ZodType<
  PayoutsGetByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  walletId: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  status: PayoutsGetByIdStatus$inboundSchema,
  amount: z.string(),
  address: z.string(),
  extraId: z.nullable(z.string()),
  txHash: z.nullable(z.string()),
  fee: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.nullable(z.lazy(() => PayoutsGetByIdCurrency$inboundSchema)),
});

/** @internal */
export type PayoutsGetByIdResponse$Outbound = {
  id: string;
  walletId: string;
  merchantId: string;
  currencyId: string;
  status: string;
  amount: string;
  address: string;
  extraId: string | null;
  txHash: string | null;
  fee: string | null;
  callbackUrl: string | null;
  createdAt: string;
  updatedAt: string;
  currency: PayoutsGetByIdCurrency$Outbound | null;
};

/** @internal */
export const PayoutsGetByIdResponse$outboundSchema: z.ZodType<
  PayoutsGetByIdResponse$Outbound,
  z.ZodTypeDef,
  PayoutsGetByIdResponse
> = z.object({
  id: z.string(),
  walletId: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  status: PayoutsGetByIdStatus$outboundSchema,
  amount: z.string(),
  address: z.string(),
  extraId: z.nullable(z.string()),
  txHash: z.nullable(z.string()),
  fee: z.nullable(z.string()),
  callbackUrl: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.nullable(z.lazy(() => PayoutsGetByIdCurrency$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutsGetByIdResponse$ {
  /** @deprecated use `PayoutsGetByIdResponse$inboundSchema` instead. */
  export const inboundSchema = PayoutsGetByIdResponse$inboundSchema;
  /** @deprecated use `PayoutsGetByIdResponse$outboundSchema` instead. */
  export const outboundSchema = PayoutsGetByIdResponse$outboundSchema;
  /** @deprecated use `PayoutsGetByIdResponse$Outbound` instead. */
  export type Outbound = PayoutsGetByIdResponse$Outbound;
}

export function payoutsGetByIdResponseToJSON(
  payoutsGetByIdResponse: PayoutsGetByIdResponse,
): string {
  return JSON.stringify(
    PayoutsGetByIdResponse$outboundSchema.parse(payoutsGetByIdResponse),
  );
}

export function payoutsGetByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayoutsGetByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutsGetByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutsGetByIdResponse' from JSON`,
  );
}
