/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WalletsListOwnedFilter = {
  createdStart?: string | null | undefined;
  createdEnd?: string | null | undefined;
  merchants?: Array<string> | null | undefined;
  q?: string | null | undefined;
};

export type WalletsListOwnedRequest = {
  filter?: WalletsListOwnedFilter | undefined;
  sort?: Array<string> | null | undefined;
  cursor?: string | undefined;
  pageSize?: number | undefined;
};

export type WalletsListOwnedCursor = string | any;

export type WalletsListOwnedMeta = {
  cursor?: string | any | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

export type WalletsListOwnedCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type WalletsListOwnedData = {
  id: string;
  merchantId: string;
  currencyId: string;
  balance: string;
  pendingBalance: string;
  createdAt: string;
  updatedAt: string;
  currency: WalletsListOwnedCurrency;
};

/**
 * Successful response
 */
export type WalletsListOwnedResponse = {
  meta: WalletsListOwnedMeta;
  data: Array<WalletsListOwnedData>;
};

/** @internal */
export const WalletsListOwnedFilter$inboundSchema: z.ZodType<
  WalletsListOwnedFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_start: z.nullable(z.string()).optional(),
  created_end: z.nullable(z.string()).optional(),
  merchants: z.nullable(z.array(z.string())).optional(),
  q: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_start": "createdStart",
    "created_end": "createdEnd",
  });
});

/** @internal */
export type WalletsListOwnedFilter$Outbound = {
  created_start?: string | null | undefined;
  created_end?: string | null | undefined;
  merchants?: Array<string> | null | undefined;
  q?: string | null | undefined;
};

/** @internal */
export const WalletsListOwnedFilter$outboundSchema: z.ZodType<
  WalletsListOwnedFilter$Outbound,
  z.ZodTypeDef,
  WalletsListOwnedFilter
> = z.object({
  createdStart: z.nullable(z.string()).optional(),
  createdEnd: z.nullable(z.string()).optional(),
  merchants: z.nullable(z.array(z.string())).optional(),
  q: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    createdStart: "created_start",
    createdEnd: "created_end",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsListOwnedFilter$ {
  /** @deprecated use `WalletsListOwnedFilter$inboundSchema` instead. */
  export const inboundSchema = WalletsListOwnedFilter$inboundSchema;
  /** @deprecated use `WalletsListOwnedFilter$outboundSchema` instead. */
  export const outboundSchema = WalletsListOwnedFilter$outboundSchema;
  /** @deprecated use `WalletsListOwnedFilter$Outbound` instead. */
  export type Outbound = WalletsListOwnedFilter$Outbound;
}

export function walletsListOwnedFilterToJSON(
  walletsListOwnedFilter: WalletsListOwnedFilter,
): string {
  return JSON.stringify(
    WalletsListOwnedFilter$outboundSchema.parse(walletsListOwnedFilter),
  );
}

export function walletsListOwnedFilterFromJSON(
  jsonString: string,
): SafeParseResult<WalletsListOwnedFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsListOwnedFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsListOwnedFilter' from JSON`,
  );
}

/** @internal */
export const WalletsListOwnedRequest$inboundSchema: z.ZodType<
  WalletsListOwnedRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filter: z.lazy(() => WalletsListOwnedFilter$inboundSchema).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  cursor: z.string().optional(),
  pageSize: z.number().optional(),
});

/** @internal */
export type WalletsListOwnedRequest$Outbound = {
  filter?: WalletsListOwnedFilter$Outbound | undefined;
  sort?: Array<string> | null | undefined;
  cursor?: string | undefined;
  pageSize?: number | undefined;
};

/** @internal */
export const WalletsListOwnedRequest$outboundSchema: z.ZodType<
  WalletsListOwnedRequest$Outbound,
  z.ZodTypeDef,
  WalletsListOwnedRequest
> = z.object({
  filter: z.lazy(() => WalletsListOwnedFilter$outboundSchema).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  cursor: z.string().optional(),
  pageSize: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsListOwnedRequest$ {
  /** @deprecated use `WalletsListOwnedRequest$inboundSchema` instead. */
  export const inboundSchema = WalletsListOwnedRequest$inboundSchema;
  /** @deprecated use `WalletsListOwnedRequest$outboundSchema` instead. */
  export const outboundSchema = WalletsListOwnedRequest$outboundSchema;
  /** @deprecated use `WalletsListOwnedRequest$Outbound` instead. */
  export type Outbound = WalletsListOwnedRequest$Outbound;
}

export function walletsListOwnedRequestToJSON(
  walletsListOwnedRequest: WalletsListOwnedRequest,
): string {
  return JSON.stringify(
    WalletsListOwnedRequest$outboundSchema.parse(walletsListOwnedRequest),
  );
}

export function walletsListOwnedRequestFromJSON(
  jsonString: string,
): SafeParseResult<WalletsListOwnedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsListOwnedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsListOwnedRequest' from JSON`,
  );
}

/** @internal */
export const WalletsListOwnedCursor$inboundSchema: z.ZodType<
  WalletsListOwnedCursor,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.any()]);

/** @internal */
export type WalletsListOwnedCursor$Outbound = string | any;

/** @internal */
export const WalletsListOwnedCursor$outboundSchema: z.ZodType<
  WalletsListOwnedCursor$Outbound,
  z.ZodTypeDef,
  WalletsListOwnedCursor
> = z.union([z.string(), z.any()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsListOwnedCursor$ {
  /** @deprecated use `WalletsListOwnedCursor$inboundSchema` instead. */
  export const inboundSchema = WalletsListOwnedCursor$inboundSchema;
  /** @deprecated use `WalletsListOwnedCursor$outboundSchema` instead. */
  export const outboundSchema = WalletsListOwnedCursor$outboundSchema;
  /** @deprecated use `WalletsListOwnedCursor$Outbound` instead. */
  export type Outbound = WalletsListOwnedCursor$Outbound;
}

export function walletsListOwnedCursorToJSON(
  walletsListOwnedCursor: WalletsListOwnedCursor,
): string {
  return JSON.stringify(
    WalletsListOwnedCursor$outboundSchema.parse(walletsListOwnedCursor),
  );
}

export function walletsListOwnedCursorFromJSON(
  jsonString: string,
): SafeParseResult<WalletsListOwnedCursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsListOwnedCursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsListOwnedCursor' from JSON`,
  );
}

/** @internal */
export const WalletsListOwnedMeta$inboundSchema: z.ZodType<
  WalletsListOwnedMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.union([z.string(), z.any()]).optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/** @internal */
export type WalletsListOwnedMeta$Outbound = {
  cursor?: string | any | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/** @internal */
export const WalletsListOwnedMeta$outboundSchema: z.ZodType<
  WalletsListOwnedMeta$Outbound,
  z.ZodTypeDef,
  WalletsListOwnedMeta
> = z.object({
  cursor: z.union([z.string(), z.any()]).optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsListOwnedMeta$ {
  /** @deprecated use `WalletsListOwnedMeta$inboundSchema` instead. */
  export const inboundSchema = WalletsListOwnedMeta$inboundSchema;
  /** @deprecated use `WalletsListOwnedMeta$outboundSchema` instead. */
  export const outboundSchema = WalletsListOwnedMeta$outboundSchema;
  /** @deprecated use `WalletsListOwnedMeta$Outbound` instead. */
  export type Outbound = WalletsListOwnedMeta$Outbound;
}

export function walletsListOwnedMetaToJSON(
  walletsListOwnedMeta: WalletsListOwnedMeta,
): string {
  return JSON.stringify(
    WalletsListOwnedMeta$outboundSchema.parse(walletsListOwnedMeta),
  );
}

export function walletsListOwnedMetaFromJSON(
  jsonString: string,
): SafeParseResult<WalletsListOwnedMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsListOwnedMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsListOwnedMeta' from JSON`,
  );
}

/** @internal */
export const WalletsListOwnedCurrency$inboundSchema: z.ZodType<
  WalletsListOwnedCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type WalletsListOwnedCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const WalletsListOwnedCurrency$outboundSchema: z.ZodType<
  WalletsListOwnedCurrency$Outbound,
  z.ZodTypeDef,
  WalletsListOwnedCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsListOwnedCurrency$ {
  /** @deprecated use `WalletsListOwnedCurrency$inboundSchema` instead. */
  export const inboundSchema = WalletsListOwnedCurrency$inboundSchema;
  /** @deprecated use `WalletsListOwnedCurrency$outboundSchema` instead. */
  export const outboundSchema = WalletsListOwnedCurrency$outboundSchema;
  /** @deprecated use `WalletsListOwnedCurrency$Outbound` instead. */
  export type Outbound = WalletsListOwnedCurrency$Outbound;
}

export function walletsListOwnedCurrencyToJSON(
  walletsListOwnedCurrency: WalletsListOwnedCurrency,
): string {
  return JSON.stringify(
    WalletsListOwnedCurrency$outboundSchema.parse(walletsListOwnedCurrency),
  );
}

export function walletsListOwnedCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<WalletsListOwnedCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsListOwnedCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsListOwnedCurrency' from JSON`,
  );
}

/** @internal */
export const WalletsListOwnedData$inboundSchema: z.ZodType<
  WalletsListOwnedData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  balance: z.string(),
  pendingBalance: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.lazy(() => WalletsListOwnedCurrency$inboundSchema),
});

/** @internal */
export type WalletsListOwnedData$Outbound = {
  id: string;
  merchantId: string;
  currencyId: string;
  balance: string;
  pendingBalance: string;
  createdAt: string;
  updatedAt: string;
  currency: WalletsListOwnedCurrency$Outbound;
};

/** @internal */
export const WalletsListOwnedData$outboundSchema: z.ZodType<
  WalletsListOwnedData$Outbound,
  z.ZodTypeDef,
  WalletsListOwnedData
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  balance: z.string(),
  pendingBalance: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.lazy(() => WalletsListOwnedCurrency$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsListOwnedData$ {
  /** @deprecated use `WalletsListOwnedData$inboundSchema` instead. */
  export const inboundSchema = WalletsListOwnedData$inboundSchema;
  /** @deprecated use `WalletsListOwnedData$outboundSchema` instead. */
  export const outboundSchema = WalletsListOwnedData$outboundSchema;
  /** @deprecated use `WalletsListOwnedData$Outbound` instead. */
  export type Outbound = WalletsListOwnedData$Outbound;
}

export function walletsListOwnedDataToJSON(
  walletsListOwnedData: WalletsListOwnedData,
): string {
  return JSON.stringify(
    WalletsListOwnedData$outboundSchema.parse(walletsListOwnedData),
  );
}

export function walletsListOwnedDataFromJSON(
  jsonString: string,
): SafeParseResult<WalletsListOwnedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsListOwnedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsListOwnedData' from JSON`,
  );
}

/** @internal */
export const WalletsListOwnedResponse$inboundSchema: z.ZodType<
  WalletsListOwnedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: z.lazy(() => WalletsListOwnedMeta$inboundSchema),
  data: z.array(z.lazy(() => WalletsListOwnedData$inboundSchema)),
});

/** @internal */
export type WalletsListOwnedResponse$Outbound = {
  meta: WalletsListOwnedMeta$Outbound;
  data: Array<WalletsListOwnedData$Outbound>;
};

/** @internal */
export const WalletsListOwnedResponse$outboundSchema: z.ZodType<
  WalletsListOwnedResponse$Outbound,
  z.ZodTypeDef,
  WalletsListOwnedResponse
> = z.object({
  meta: z.lazy(() => WalletsListOwnedMeta$outboundSchema),
  data: z.array(z.lazy(() => WalletsListOwnedData$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsListOwnedResponse$ {
  /** @deprecated use `WalletsListOwnedResponse$inboundSchema` instead. */
  export const inboundSchema = WalletsListOwnedResponse$inboundSchema;
  /** @deprecated use `WalletsListOwnedResponse$outboundSchema` instead. */
  export const outboundSchema = WalletsListOwnedResponse$outboundSchema;
  /** @deprecated use `WalletsListOwnedResponse$Outbound` instead. */
  export type Outbound = WalletsListOwnedResponse$Outbound;
}

export function walletsListOwnedResponseToJSON(
  walletsListOwnedResponse: WalletsListOwnedResponse,
): string {
  return JSON.stringify(
    WalletsListOwnedResponse$outboundSchema.parse(walletsListOwnedResponse),
  );
}

export function walletsListOwnedResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletsListOwnedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsListOwnedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsListOwnedResponse' from JSON`,
  );
}
