/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Successful response
 */
export type WalletsGetStatsResponse = {
  total: number;
  totalUSDValue: number;
  totalAvailableUSDValue: number;
  totalPendingUSDValue: number;
};

/** @internal */
export const WalletsGetStatsResponse$inboundSchema: z.ZodType<
  WalletsGetStatsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number(),
  totalUSDValue: z.number(),
  totalAvailableUSDValue: z.number(),
  totalPendingUSDValue: z.number(),
});

/** @internal */
export type WalletsGetStatsResponse$Outbound = {
  total: number;
  totalUSDValue: number;
  totalAvailableUSDValue: number;
  totalPendingUSDValue: number;
};

/** @internal */
export const WalletsGetStatsResponse$outboundSchema: z.ZodType<
  WalletsGetStatsResponse$Outbound,
  z.ZodTypeDef,
  WalletsGetStatsResponse
> = z.object({
  total: z.number(),
  totalUSDValue: z.number(),
  totalAvailableUSDValue: z.number(),
  totalPendingUSDValue: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsGetStatsResponse$ {
  /** @deprecated use `WalletsGetStatsResponse$inboundSchema` instead. */
  export const inboundSchema = WalletsGetStatsResponse$inboundSchema;
  /** @deprecated use `WalletsGetStatsResponse$outboundSchema` instead. */
  export const outboundSchema = WalletsGetStatsResponse$outboundSchema;
  /** @deprecated use `WalletsGetStatsResponse$Outbound` instead. */
  export type Outbound = WalletsGetStatsResponse$Outbound;
}

export function walletsGetStatsResponseToJSON(
  walletsGetStatsResponse: WalletsGetStatsResponse,
): string {
  return JSON.stringify(
    WalletsGetStatsResponse$outboundSchema.parse(walletsGetStatsResponse),
  );
}

export function walletsGetStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletsGetStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsGetStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsGetStatsResponse' from JSON`,
  );
}
