/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WalletsGetAllOwnedCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

export type WalletsGetAllOwnedResponse = {
  id: string;
  merchantId: string;
  currencyId: string;
  balance: string;
  pendingBalance: string;
  createdAt: string;
  updatedAt: string;
  currency: WalletsGetAllOwnedCurrency;
};

/** @internal */
export const WalletsGetAllOwnedCurrency$inboundSchema: z.ZodType<
  WalletsGetAllOwnedCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type WalletsGetAllOwnedCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const WalletsGetAllOwnedCurrency$outboundSchema: z.ZodType<
  WalletsGetAllOwnedCurrency$Outbound,
  z.ZodTypeDef,
  WalletsGetAllOwnedCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsGetAllOwnedCurrency$ {
  /** @deprecated use `WalletsGetAllOwnedCurrency$inboundSchema` instead. */
  export const inboundSchema = WalletsGetAllOwnedCurrency$inboundSchema;
  /** @deprecated use `WalletsGetAllOwnedCurrency$outboundSchema` instead. */
  export const outboundSchema = WalletsGetAllOwnedCurrency$outboundSchema;
  /** @deprecated use `WalletsGetAllOwnedCurrency$Outbound` instead. */
  export type Outbound = WalletsGetAllOwnedCurrency$Outbound;
}

export function walletsGetAllOwnedCurrencyToJSON(
  walletsGetAllOwnedCurrency: WalletsGetAllOwnedCurrency,
): string {
  return JSON.stringify(
    WalletsGetAllOwnedCurrency$outboundSchema.parse(walletsGetAllOwnedCurrency),
  );
}

export function walletsGetAllOwnedCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<WalletsGetAllOwnedCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsGetAllOwnedCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsGetAllOwnedCurrency' from JSON`,
  );
}

/** @internal */
export const WalletsGetAllOwnedResponse$inboundSchema: z.ZodType<
  WalletsGetAllOwnedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  balance: z.string(),
  pendingBalance: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.lazy(() => WalletsGetAllOwnedCurrency$inboundSchema),
});

/** @internal */
export type WalletsGetAllOwnedResponse$Outbound = {
  id: string;
  merchantId: string;
  currencyId: string;
  balance: string;
  pendingBalance: string;
  createdAt: string;
  updatedAt: string;
  currency: WalletsGetAllOwnedCurrency$Outbound;
};

/** @internal */
export const WalletsGetAllOwnedResponse$outboundSchema: z.ZodType<
  WalletsGetAllOwnedResponse$Outbound,
  z.ZodTypeDef,
  WalletsGetAllOwnedResponse
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  balance: z.string(),
  pendingBalance: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.lazy(() => WalletsGetAllOwnedCurrency$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsGetAllOwnedResponse$ {
  /** @deprecated use `WalletsGetAllOwnedResponse$inboundSchema` instead. */
  export const inboundSchema = WalletsGetAllOwnedResponse$inboundSchema;
  /** @deprecated use `WalletsGetAllOwnedResponse$outboundSchema` instead. */
  export const outboundSchema = WalletsGetAllOwnedResponse$outboundSchema;
  /** @deprecated use `WalletsGetAllOwnedResponse$Outbound` instead. */
  export type Outbound = WalletsGetAllOwnedResponse$Outbound;
}

export function walletsGetAllOwnedResponseToJSON(
  walletsGetAllOwnedResponse: WalletsGetAllOwnedResponse,
): string {
  return JSON.stringify(
    WalletsGetAllOwnedResponse$outboundSchema.parse(walletsGetAllOwnedResponse),
  );
}

export function walletsGetAllOwnedResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletsGetAllOwnedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsGetAllOwnedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsGetAllOwnedResponse' from JSON`,
  );
}
