/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WalletsGetByIdRequest = {
  id: string;
};

export type WalletsGetByIdCurrency = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * Successful response
 */
export type WalletsGetByIdResponse = {
  id: string;
  merchantId: string;
  currencyId: string;
  balance: string;
  pendingBalance: string;
  createdAt: string;
  updatedAt: string;
  currency: WalletsGetByIdCurrency;
};

/** @internal */
export const WalletsGetByIdRequest$inboundSchema: z.ZodType<
  WalletsGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type WalletsGetByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const WalletsGetByIdRequest$outboundSchema: z.ZodType<
  WalletsGetByIdRequest$Outbound,
  z.ZodTypeDef,
  WalletsGetByIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsGetByIdRequest$ {
  /** @deprecated use `WalletsGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = WalletsGetByIdRequest$inboundSchema;
  /** @deprecated use `WalletsGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = WalletsGetByIdRequest$outboundSchema;
  /** @deprecated use `WalletsGetByIdRequest$Outbound` instead. */
  export type Outbound = WalletsGetByIdRequest$Outbound;
}

export function walletsGetByIdRequestToJSON(
  walletsGetByIdRequest: WalletsGetByIdRequest,
): string {
  return JSON.stringify(
    WalletsGetByIdRequest$outboundSchema.parse(walletsGetByIdRequest),
  );
}

export function walletsGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<WalletsGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsGetByIdRequest' from JSON`,
  );
}

/** @internal */
export const WalletsGetByIdCurrency$inboundSchema: z.ZodType<
  WalletsGetByIdCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type WalletsGetByIdCurrency$Outbound = {
  id: string;
  code: string;
  name: string;
  enabled: boolean;
  walletRegex: string;
  priority: number;
  extraIdExists: boolean;
  extraIdRegex: string | null;
  usdPrice: string;
  minPaymentAmount: string;
  minPayoutAmount: string;
  minWithdrawalFeeEstimate: string;
  logoUrl: string | null;
  track: boolean;
  cgId: string | null;
  isMaxlimit: boolean;
  network: string | null;
  smartContract: string | null;
  networkPrecision: string | null;
  explorerLinkHash: string | null;
  precision: number;
  ticker: string | null;
  isDefi: boolean;
  isPopular: boolean;
  isStable: boolean;
  availableForToConversion: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const WalletsGetByIdCurrency$outboundSchema: z.ZodType<
  WalletsGetByIdCurrency$Outbound,
  z.ZodTypeDef,
  WalletsGetByIdCurrency
> = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  enabled: z.boolean(),
  walletRegex: z.string(),
  priority: z.number().int(),
  extraIdExists: z.boolean(),
  extraIdRegex: z.nullable(z.string()),
  usdPrice: z.string(),
  minPaymentAmount: z.string(),
  minPayoutAmount: z.string(),
  minWithdrawalFeeEstimate: z.string(),
  logoUrl: z.nullable(z.string()),
  track: z.boolean(),
  cgId: z.nullable(z.string()),
  isMaxlimit: z.boolean(),
  network: z.nullable(z.string()),
  smartContract: z.nullable(z.string()),
  networkPrecision: z.nullable(z.string()),
  explorerLinkHash: z.nullable(z.string()),
  precision: z.number().int(),
  ticker: z.nullable(z.string()),
  isDefi: z.boolean(),
  isPopular: z.boolean(),
  isStable: z.boolean(),
  availableForToConversion: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsGetByIdCurrency$ {
  /** @deprecated use `WalletsGetByIdCurrency$inboundSchema` instead. */
  export const inboundSchema = WalletsGetByIdCurrency$inboundSchema;
  /** @deprecated use `WalletsGetByIdCurrency$outboundSchema` instead. */
  export const outboundSchema = WalletsGetByIdCurrency$outboundSchema;
  /** @deprecated use `WalletsGetByIdCurrency$Outbound` instead. */
  export type Outbound = WalletsGetByIdCurrency$Outbound;
}

export function walletsGetByIdCurrencyToJSON(
  walletsGetByIdCurrency: WalletsGetByIdCurrency,
): string {
  return JSON.stringify(
    WalletsGetByIdCurrency$outboundSchema.parse(walletsGetByIdCurrency),
  );
}

export function walletsGetByIdCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<WalletsGetByIdCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsGetByIdCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsGetByIdCurrency' from JSON`,
  );
}

/** @internal */
export const WalletsGetByIdResponse$inboundSchema: z.ZodType<
  WalletsGetByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  balance: z.string(),
  pendingBalance: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.lazy(() => WalletsGetByIdCurrency$inboundSchema),
});

/** @internal */
export type WalletsGetByIdResponse$Outbound = {
  id: string;
  merchantId: string;
  currencyId: string;
  balance: string;
  pendingBalance: string;
  createdAt: string;
  updatedAt: string;
  currency: WalletsGetByIdCurrency$Outbound;
};

/** @internal */
export const WalletsGetByIdResponse$outboundSchema: z.ZodType<
  WalletsGetByIdResponse$Outbound,
  z.ZodTypeDef,
  WalletsGetByIdResponse
> = z.object({
  id: z.string(),
  merchantId: z.string(),
  currencyId: z.string(),
  balance: z.string(),
  pendingBalance: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  currency: z.lazy(() => WalletsGetByIdCurrency$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsGetByIdResponse$ {
  /** @deprecated use `WalletsGetByIdResponse$inboundSchema` instead. */
  export const inboundSchema = WalletsGetByIdResponse$inboundSchema;
  /** @deprecated use `WalletsGetByIdResponse$outboundSchema` instead. */
  export const outboundSchema = WalletsGetByIdResponse$outboundSchema;
  /** @deprecated use `WalletsGetByIdResponse$Outbound` instead. */
  export type Outbound = WalletsGetByIdResponse$Outbound;
}

export function walletsGetByIdResponseToJSON(
  walletsGetByIdResponse: WalletsGetByIdResponse,
): string {
  return JSON.stringify(
    WalletsGetByIdResponse$outboundSchema.parse(walletsGetByIdResponse),
  );
}

export function walletsGetByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletsGetByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsGetByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsGetByIdResponse' from JSON`,
  );
}
