/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ErrorBADREQUESTIssue = {
  message: string;
};

/** @internal */
export const ErrorBADREQUESTIssue$inboundSchema: z.ZodType<
  ErrorBADREQUESTIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type ErrorBADREQUESTIssue$Outbound = {
  message: string;
};

/** @internal */
export const ErrorBADREQUESTIssue$outboundSchema: z.ZodType<
  ErrorBADREQUESTIssue$Outbound,
  z.ZodTypeDef,
  ErrorBADREQUESTIssue
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorBADREQUESTIssue$ {
  /** @deprecated use `ErrorBADREQUESTIssue$inboundSchema` instead. */
  export const inboundSchema = ErrorBADREQUESTIssue$inboundSchema;
  /** @deprecated use `ErrorBADREQUESTIssue$outboundSchema` instead. */
  export const outboundSchema = ErrorBADREQUESTIssue$outboundSchema;
  /** @deprecated use `ErrorBADREQUESTIssue$Outbound` instead. */
  export type Outbound = ErrorBADREQUESTIssue$Outbound;
}

export function errorBADREQUESTIssueToJSON(
  errorBADREQUESTIssue: ErrorBADREQUESTIssue,
): string {
  return JSON.stringify(
    ErrorBADREQUESTIssue$outboundSchema.parse(errorBADREQUESTIssue),
  );
}

export function errorBADREQUESTIssueFromJSON(
  jsonString: string,
): SafeParseResult<ErrorBADREQUESTIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorBADREQUESTIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorBADREQUESTIssue' from JSON`,
  );
}
