/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ERRORINTERNALSERVERERRORIssue = {
  message: string;
};

/** @internal */
export const ERRORINTERNALSERVERERRORIssue$inboundSchema: z.ZodType<
  ERRORINTERNALSERVERERRORIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type ERRORINTERNALSERVERERRORIssue$Outbound = {
  message: string;
};

/** @internal */
export const ERRORINTERNALSERVERERRORIssue$outboundSchema: z.ZodType<
  ERRORINTERNALSERVERERRORIssue$Outbound,
  z.ZodTypeDef,
  ERRORINTERNALSERVERERRORIssue
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ERRORINTERNALSERVERERRORIssue$ {
  /** @deprecated use `ERRORINTERNALSERVERERRORIssue$inboundSchema` instead. */
  export const inboundSchema = ERRORINTERNALSERVERERRORIssue$inboundSchema;
  /** @deprecated use `ERRORINTERNALSERVERERRORIssue$outboundSchema` instead. */
  export const outboundSchema = ERRORINTERNALSERVERERRORIssue$outboundSchema;
  /** @deprecated use `ERRORINTERNALSERVERERRORIssue$Outbound` instead. */
  export type Outbound = ERRORINTERNALSERVERERRORIssue$Outbound;
}

export function errorINTERNALSERVERERRORIssueToJSON(
  errorinternalservererrorIssue: ERRORINTERNALSERVERERRORIssue,
): string {
  return JSON.stringify(
    ERRORINTERNALSERVERERRORIssue$outboundSchema.parse(
      errorinternalservererrorIssue,
    ),
  );
}

export function errorINTERNALSERVERERRORIssueFromJSON(
  jsonString: string,
): SafeParseResult<ERRORINTERNALSERVERERRORIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ERRORINTERNALSERVERERRORIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ERRORINTERNALSERVERERRORIssue' from JSON`,
  );
}
