/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ErrorUNAUTHORIZEDIssue = {
  message: string;
};

/** @internal */
export const ErrorUNAUTHORIZEDIssue$inboundSchema: z.ZodType<
  ErrorUNAUTHORIZEDIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type ErrorUNAUTHORIZEDIssue$Outbound = {
  message: string;
};

/** @internal */
export const ErrorUNAUTHORIZEDIssue$outboundSchema: z.ZodType<
  ErrorUNAUTHORIZEDIssue$Outbound,
  z.ZodTypeDef,
  ErrorUNAUTHORIZEDIssue
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorUNAUTHORIZEDIssue$ {
  /** @deprecated use `ErrorUNAUTHORIZEDIssue$inboundSchema` instead. */
  export const inboundSchema = ErrorUNAUTHORIZEDIssue$inboundSchema;
  /** @deprecated use `ErrorUNAUTHORIZEDIssue$outboundSchema` instead. */
  export const outboundSchema = ErrorUNAUTHORIZEDIssue$outboundSchema;
  /** @deprecated use `ErrorUNAUTHORIZEDIssue$Outbound` instead. */
  export type Outbound = ErrorUNAUTHORIZEDIssue$Outbound;
}

export function errorUNAUTHORIZEDIssueToJSON(
  errorUNAUTHORIZEDIssue: ErrorUNAUTHORIZEDIssue,
): string {
  return JSON.stringify(
    ErrorUNAUTHORIZEDIssue$outboundSchema.parse(errorUNAUTHORIZEDIssue),
  );
}

export function errorUNAUTHORIZEDIssueFromJSON(
  jsonString: string,
): SafeParseResult<ErrorUNAUTHORIZEDIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorUNAUTHORIZEDIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorUNAUTHORIZEDIssue' from JSON`,
  );
}
