/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ErrorFORBIDDENIssue = {
  message: string;
};

/** @internal */
export const ErrorFORBIDDENIssue$inboundSchema: z.ZodType<
  ErrorFORBIDDENIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type ErrorFORBIDDENIssue$Outbound = {
  message: string;
};

/** @internal */
export const ErrorFORBIDDENIssue$outboundSchema: z.ZodType<
  ErrorFORBIDDENIssue$Outbound,
  z.ZodTypeDef,
  ErrorFORBIDDENIssue
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorFORBIDDENIssue$ {
  /** @deprecated use `ErrorFORBIDDENIssue$inboundSchema` instead. */
  export const inboundSchema = ErrorFORBIDDENIssue$inboundSchema;
  /** @deprecated use `ErrorFORBIDDENIssue$outboundSchema` instead. */
  export const outboundSchema = ErrorFORBIDDENIssue$outboundSchema;
  /** @deprecated use `ErrorFORBIDDENIssue$Outbound` instead. */
  export type Outbound = ErrorFORBIDDENIssue$Outbound;
}

export function errorFORBIDDENIssueToJSON(
  errorFORBIDDENIssue: ErrorFORBIDDENIssue,
): string {
  return JSON.stringify(
    ErrorFORBIDDENIssue$outboundSchema.parse(errorFORBIDDENIssue),
  );
}

export function errorFORBIDDENIssueFromJSON(
  jsonString: string,
): SafeParseResult<ErrorFORBIDDENIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorFORBIDDENIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorFORBIDDENIssue' from JSON`,
  );
}
