/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ErrorNOTFOUNDIssue = {
  message: string;
};

/** @internal */
export const ErrorNOTFOUNDIssue$inboundSchema: z.ZodType<
  ErrorNOTFOUNDIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type ErrorNOTFOUNDIssue$Outbound = {
  message: string;
};

/** @internal */
export const ErrorNOTFOUNDIssue$outboundSchema: z.ZodType<
  ErrorNOTFOUNDIssue$Outbound,
  z.ZodTypeDef,
  ErrorNOTFOUNDIssue
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorNOTFOUNDIssue$ {
  /** @deprecated use `ErrorNOTFOUNDIssue$inboundSchema` instead. */
  export const inboundSchema = ErrorNOTFOUNDIssue$inboundSchema;
  /** @deprecated use `ErrorNOTFOUNDIssue$outboundSchema` instead. */
  export const outboundSchema = ErrorNOTFOUNDIssue$outboundSchema;
  /** @deprecated use `ErrorNOTFOUNDIssue$Outbound` instead. */
  export type Outbound = ErrorNOTFOUNDIssue$Outbound;
}

export function errorNOTFOUNDIssueToJSON(
  errorNOTFOUNDIssue: ErrorNOTFOUNDIssue,
): string {
  return JSON.stringify(
    ErrorNOTFOUNDIssue$outboundSchema.parse(errorNOTFOUNDIssue),
  );
}

export function errorNOTFOUNDIssueFromJSON(
  jsonString: string,
): SafeParseResult<ErrorNOTFOUNDIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorNOTFOUNDIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorNOTFOUNDIssue' from JSON`,
  );
}
